### ISSUE TITLE
Incompatibility Pyglet 1.5.0 and Python 3.7

### ISSUE THREAD

**Issue by HenkoBeukes** [pyglet/pyglet#153] opened 2020-02-28 08:13 UTC
I have a 3D plotter program written in Python 3.6 using Pyglet 1.3.3 on Linux Ubuntu 18.04.
This worked fine without issues. 
When I upgraded to Python 3.7.6 using  Pyglet 1.3.3 I found this exception:

Traceback (most recent call last):
  File "/home/henko/Python/my_3D_plotter.py", line 14, in <module>
    from pyglet.gl import *
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 221, in <module>
    from .xlib import XlibConfig as Config
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 12, in <module>
    from pyglet.canvas.xlib import XlibCanvas
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
    from pyglet.canvas.xlib import XlibDisplay as Display
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 19, in <module>
    from . import xlib_vidmoderestore
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/canvas/xlib_vidmoderestore.py", line 23, in <module>
    from pyglet.libs.x11 import xlib
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/libs/x11/xlib.py", line 2928, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

I then upgraded to Pyglet 1.5.0 and got the following:
Python3.7.6
Pyglet 1.5.0

Exception ignored in: <function WeakMethod.__new__.<locals>._cb at 0x7f1b030de4d0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/weakref.py", line 58, in _cb
  File "/home/henko/.local/lib/python3.7/site-packages/pyglet/event.py", line 356, in _remove_handler
  File "/usr/lib/python3.7/weakref.py", line 74, in __eq__
TypeError: isinstance() arg 2 must be a type or tuple of types

This exception does not exit the program, but runs it, only giving this exception report multiple times upon controlled exit. 

A similar exception occurs with Python 3.6 and Pyglet 1.5.0
The fact that an older Python version finds a problem as well makes me think the problem is with the newer Pyglet versions.  
This seems similar to this issue: 
xlib support broken in Python 3.7.6 (and possibly other new Python releases) #112

**Comment by benmoran56** [comment] 2020-03-01 01:19
Thanks for opening the ticket. 

The first error is related to #112, and is fixed in pyglet releases > 4.9. This was caused by some changes in recent Python point releases. 

The second error you're experiencing maybe be caused by a change to the way the event system works in pyglet 1.4.x+. In order to correct issues with circular references, the event dispatchers now only hold weak references to handlers. Where in the past this would work: 
```
window.push_handlers(MyHandler())
```
It will no longer work because there is no reference "MyHandler" anywhere, so it gets garbage collected. Instead, something like this would be necessary: 
```
my_handler = MyHandler()
window.push_handlers(my_handler)
```
Are you using this pattern in your code anywhere? If so that could be the cause. If that's not it, do you have a link to some example code where this error occurs? That would help in figuring it out.

**Comment by HenkoBeukes** [comment] 2020-03-01 12:25
I do not use explicit event handlers so the given pattern does not appear
in my code.
I do use a few event types like: on_key_press, on_key_release and
on_mouse_drag, as methods inside the window class.

I will try to put the project on github in a day or two.

Regards
Henko

**Comment by HenkoBeukes** [comment] 2020-03-02 13:45
Benjamin

Here is the link to my github repository of the plotter:
https://github.com/HenkoBeukes/pyglet-3D-plotter

Regards
Henko

**Comment by HenkoBeukes** [comment] 2020-03-03 12:33
The following is the abbreviated pattern of my 3d plotter.
The main window, MyWindow, opens on start-up. By pressing p all activity in MyWindow is suspended and a text window, TextWindow, opens. This allows for the equation to be entered. Press enter and the TextWindow closes, the equation is plotted in MyWindow. 
When I then close the app the series of exception reports are given.

import pyglet
from pyglet.gl import *
from pyglet.window import key, mouse, FPSDisplay


class TextWindow(pyglet.window.Window):
    def __init__(self, window_x,  window_y, *args, **kwargs):
        super().__init__(*args, **kwargs)
    	...
       # position A

    def on_key_press(self, symbol, modifiers):  # input handler
        if symbol == key.ESCAPE:  # closes the whole  app - Escape!
            pyglet.app.exit()

        if symbol == key.RETURN:
            c = window.color_rotate.pop(0)
            window.color_rotate.append(c)
            window.rotate_axis = 1
            window.active = 1
            render_equation(self.eq, colors[c])
            self.close()

	if symbol == ...
	...

    def on_close(self): 
        window.rotate_axis = 1
        self.close()

    def on_draw(self):
	...

    def update(self, dt):
        ...


class MyWindow(pyglet.window.Window):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_minimum_size(200, 100)
        self.frame_rate = 1 / 60
        self.fps_display = FPSDisplay(self)

    def on_key_press(self, symbol, modifiers):
        if symbol == key.ESCAPE:
            # exits the app
            pyglet.app.exit()

        if symbol == key.P:
            self.rotate_axis = 0
            # opens the text input panel
            text_panel = TextWindow(100, 100, vsync=True)
            text_panel.set_location(self.window_x, self.window_y - 28)

    def on_key_release(self, symbol, modifiers):
	...
        
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers):
	...

    def on_mouse_scroll(self, x, y, scroll_x, scroll_y):
	...

    def on_draw(self):
	...

    def update(self, dt):
	...

    def on_resize(self, width, height):
        glViewport(0, 0, width, height)


if __name__ == '__main__':
     window = MyWindow(1400, 800, 'My Window', resizable=False, vsync=False)
    pyglet.app.run()


 
I found that by putting the line: 
	self.push_handlers(self.on_close)  
in the TextWindow init (at position A)the issue seems to be resolved. But, it seems to be only a work-around, as the choice of handler in the line is significant. If I put self.on_key_press ipo self.on_close the handler runs the event twice, i.e. the letter is recorded twice, which breaks my app.  
I have not checked all the possible events, but suspect it would be the same with all of them. The choice of self.on_close seems to have no observable side-effect. 
So, I suspect,  TextWindow(pyglet.window.Window) dispatches the events and then the call to push_handlers does it again. 

I suspect that the use of the event functions in the TextWindow does not fully override the event handlers but leaves the EventDispatcher dangling. So when I close the window the EventDispatcher wants to do its thing, but finds the handler not in the correct format and then throws the exception. I may be wrong, still getting to know the pyglet code.

**Comment by FatalThrust** [comment] 2020-03-26 22:46
there is also a issue where the garbage collector will gc sprites in a subclass unless you explicitly define a reference to the sprite object preventing the sprite from being garbage collected which seems to be a compatibility issue as well in 3.7/3.8

**Comment by benmoran56** [comment] 2020-05-04 07:05
There have been some changes to fix an issue with event handlers on subclasses. Could you give it a try again on the latest 1.5.5 release, and see how it goes?

**Comment by HenkoBeukes** [comment] 2020-05-04 07:55
I have tried it with 1.5.5 and python3.7 and the same issues still persist.  
No changes in the behavior at all.

Regards
Henko

**Comment by benmoran56** [comment] 2020-05-08 01:50
Hi Henko, 

I've tried your application on the latest pyglet 1.5.5 release, and it does not seem to have any issues with exceptions. Are you still seeing them in the console? If so, can you confirm that you are indeed using v1.5.5 by checking `pyglet.version`?

With regards to Sprites being garbage collected, it is expected behavior for that to happen unless you keep a reference to it. 

> So, I suspect, TextWindow(pyglet.window.Window) dispatches the events and then the call to 
> push_handlers does it again.
> 
> I suspect that the use of the event functions in the TextWindow does not fully override the event handlers but leaves the EventDispatcher dangling. So when I close the window the EventDispatcher wants to do its thing, but finds the handler not in the correct format and then throws the exception. I may be wrong, still getting to know the pyglet code.

The event handlers operate as a stack. Pushing a handler will add it to the stack, but will not replace the default handler (if any). Have a look at the event dispatcher documentation here for more detailed explanation: https://pyglet.readthedocs.io/en/latest/programming_guide/events.html

**Comment by benmoran56** [comment] 2021-04-19 08:11
Closing for now due to lack of reply, but please follow up if you're still having issues.

**Closed by benmoran56** 2021-04-19 08:11 UTC
