### ISSUE TITLE
Shift modifier not recognized when there are multiple windows

### ISSUE THREAD

**Issue by AparaV** [pyglet/pyglet#450] opened 2021-08-30 18:08 UTC
I noticed that when I create two windows and close the second window, the first window no longer recognizes shift modifiers being pressed. Here is some sample code

```
import pyglet
from pyglet.window import key

window = pyglet.window.Window(width=600, height=600)
window2 = pyglet.window.Window(width=400, height=400)

@window.event
def on_key_press(symbol, modifiers):
    print(f"Modifiers with key press on 1: {key.modifiers_string(modifiers)}")

@window2.event
def on_key_press(symbol, modifiers):
    print(f"Modifiers with key press on 2: {key.modifiers_string(modifiers)}")

@window.event
def on_mouse_press(x, y, buttons, modifiers):
    print(f"Modifiers with mouse press on 1: {key.modifiers_string(modifiers)}")
    
@window2.event
def on_mouse_press(x, y, buttons, modifiers):
    print(f"Modifiers with mouse press on 2: {key.modifiers_string(modifiers)}")

pyglet.app.run()
```

After I close `window2`, `window` no longer responds to `MOD_SHIFT`. It recognizes all other modifiers. But if I close `window` first, `window2` still response to `MOD_SHIFT`. Before closing either window, `MOD_SHIFT` works fine. So it is only the first window to be initialized that's facing this issue.

Am I instantiating multiple windows incorrectly? Any help is appreciated!

Thank you for your help!

Edit: I am using pyglet-1.5.19 in Python 3.9.5 on Windows 10

**Comment by benmoran56** [comment] 2021-08-31 02:38
Thanks for opening the ticket. I was able to reproduce this on my Windows 10 VM.

**Comment by caffeinepills** [comment] 2021-09-10 16:54
Could you both try the latest fix mentioned in my PR above? Works on my Windows 10 machine.

**Comment by AparaV** [comment] 2021-09-18 22:39
Yes, this fix works on my Windows 10 machine as well!

**Comment by caffeinepills** [comment] 2021-09-23 23:45
@AparaV Thanks for the test, one last thing. Could you try https://github.com/pyglet/pyglet/pull/472 and see if this PR still works with shift on both windows? I tried a different method.

**Comment by AparaV** [comment] 2021-09-28 22:53
#472 works as well!

**Comment by caffeinepills** [comment] 2022-04-10 00:53
Closing this as it seems to be resolved now. Thanks!

**Closed by caffeinepills** 2022-04-10 00:53 UTC
Labels: windows, reproducible
