### ISSUE TITLE
Memory Leak on Windows when playing audio files

### ISSUE THREAD

**Issue by HauseMasterZ** [pyglet/pyglet#926] opened 2023-08-16 09:07 UTC
When using pyglet.media to play a playlist of music audio files on Windows, memory usage continually increases by around 2-10 MB for every audio file based on its length. This is happening both when streaming is set to True or False.
I have tested on .m4a .mp3 and .wav file and all of them exhibit this behaviour.

OS: Windows 10 22H2
Python: 3.11.4
pyglet.version: 2.0.9

The following code reproduces the error. It reads from a folder and then loads the audio files using media.load and then queues it to the player. The program initially consumes around 40MB but for each new song that is played it grows by 2-10MB everytime without any stopping.

This issue is very similar to [this](https://github.com/pyglet/pyglet/issues/283) but it has been marked as solved yet I am still facing this issue in the latest pyglet version.

```
import pyglet
import os

path = 'path/to/music/folder' #change this to the path to your music folder

pool = []
audio = set('.mp3 .wav .ogg .flac .m4a'.split(' '))
for root, dirs, files in os.walk(path, followlinks = True) :
  for name in files:
    if os.path.splitext(name)[1] in audio :
        pool.append(os.path.join(root, name))

player = pyglet.media.Player()

def queue_next() :
  s = pool.pop(0)
  print("Queueing: %s" % (s))
  player.queue(pyglet.media.load(s, streaming = True))
  pool.append(s) 

def on_eos() :
  player.next_source()
  queue_next()

player.on_eos = on_eos

queue_next()
queue_next()
player.play()

window = pyglet.window.Window(100,100,)


pyglet.app.run()
```

**Comment by caffeinepills** [comment] 2023-08-16 20:45
The issue referencing is regards to Linux, not Windows, so that is not related unfortunately.

We need a little more information, what kind of files are you mostly testing? Each of the difference formats have different decoders, so it may just be one affected or multiple.

**Comment by benmoran56** [comment] 2023-08-17 01:28
Just to add, there are two potential areas for memory leaking:  The audio backend, and the decoders. 

I would recommend to first start with Wave files ONLY (the source type should show as `pyglet.media.codecs.wave.WaveSource`). This decoder doesn't have any chance of leaks as it's just a simple byte reader.

If the leaks go away, then it's likely an issue with the decoder being used. Please provide the info as caffeinepills requested. 

If you are still seeing leaks, it _could_ be an issue with the default audio backend (which is XAudio2 on Windows). Try manually switching to the legacy DirectSound backend to see if there is any improvement:
```py
import pyglet
pyglet.options['audio'] = ('directsound', 'silent')

print(pyglet.media.get_audio_driver())     # This should show DirectSound
```

**Comment by Square789** [comment] 2023-08-17 05:50
I played around with this a bit in a VM, and while i think the issue may only be about the on-load leak, but there also is a continuous leak only present in XAudio2.
Added some controllability with:
```py
window = pyglet.window.Window(100, 100)
@window.event
def on_key_press(sym, mod):
  global previous_ss
  if sym == pyglet.window.key.A:
    on_eos()
  elif sym == pyglet.window.key.Q:
    ss = tracemalloc.take_snapshot()
    if previous_ss is not None:
      print(*ss.compare_to(previous_ss, "lineno")[:20], sep="\n")
    previous_ss = ss
```
Here's [three tracemalloc](https://github.com/pyglet/pyglet/files/12365544/tracemalloc_xaudio.txt) reports taken around 15 minutes apart from eachother while playing using XAudio2, the most glaring lines are
```
<unknown>:0: size=1793 KiB (+1339 KiB), count=5185 (+3896), average=354 B
<unknown>:0: size=32.8 MiB (+31.0 MiB), count=97592 (+92407), average=352 B
<unknown>:0: size=82.1 MiB (+49.4 MiB), count=244631 (+147039), average=352 B
```
Before the first snapshot, i queued 14 audio files; between the first and second one, 2 additional ones. Between the second and third snapshot, one additional file was queued. Those also triggered the 2-10MB (as reported by Task Manager) leaks as reported by HauseMaster, but the bulk was accumulated by continuous playing.
Task manager however reported upwards of 300MB of memory usage, which would correspond to somewhere around ~25min of 44100Hz stereo with the initial process usage being somewhere around 40MB, hinting at the entire uncompressed audio being leaked.
| | Directsound | XAudio2 |
| --- | --- | --- |
| Leak on new source | X | X |
| Continuous leaks while playing | | X |

I only observed m4a, wav and mp3 files in my music folders, and enqueueing a m4a file bumps up the TM-reported usage by about 6 times of when a wav or mp3 was queued. It is likely it's related to filesize or the internals of the file somehow. The few 20min+ mp3s i do have are still of an equal influence of ~2min m4as, and relatively short m4as still can add an extreme of 6MB.
[Tracemalloc does not seem to catch these allocations.](https://github.com/pyglet/pyglet/files/12365773/tracemalloc_ds_load.txt) (~100 files queued, TM-reported usage at ~200MB). On XAudio2, loading around ~100 files yields this line `<unknown>:0: size=8248 Kib (+7818 KiB), count=23964, average=352 B` again, but is likely to be prebuffered leaked playback data, not related to the on-load leak.
While writing this, i got the idea that the WMFDecoder may be at fault, and it likely is. I could only try wav files without it, but using the standard wav decoder didn't add any memory usage at all. This issue has pretty great timing, since i was just working on XAudio2 [over here](https://github.com/Square789/pyglet/commits/audio_shenanigans) anyways.

Feel free to assign me to the issue, i am going to try to fix both the WMFDecoder initialization as well as XAudio2 playback leak.

**Comment by benmoran56** [comment] 2023-08-17 06:30
Great work!
> While writing this, i got the idea that the WMFDecoder may be at fault, and it likely is. I could only try wav files without it, but using the standard wav decoder didn't add any memory usage at all.

So if i'm understanding correctly, no leakage when using only `wav` files?

**Comment by HauseMasterZ** [comment] 2023-08-17 08:13
> The issue referencing is regards to Linux, not Windows, so that is not related unfortunately.
> 
> We need a little more information, is it WAV or MP3 specifically? Are you using FFMPEG? Each of the different audio formats may have different decoders, and some have multiple decoders.
> 
> You can check what kind of decoder by printing the source, which will return it's source class.
> 
> ```python
> src = pyglet.media.load(s, streaming = True)
> print(src)
> ```



It is happening with both .wav and .mp3 files



I am NOT using ffmpeg. These are the decoders i got while printing the source object:

For .mp3:
```
<pyglet.media.codecs.wmf.WMFSource object at 0x000001B06DBF6390>
```

For .wav:
```
<pyglet.media.codecs.wave.WaveSource object at 0x00000169113B8F50>
```

**Comment by HauseMasterZ** [comment] 2023-08-17 08:21
> Just to add, there are two potential areas for memory leaking: The audio backend, and the decoders.
> 
> I would recommend to first start with Wave files ONLY (the source type should show as `pyglet.media.codecs.wave.WaveSource`). This decoder doesn't have any chance of leaks as it's just a simple byte reader.
> 
> If the leaks go away, then it's likely an issue with the decoder being used. Please provide the info as caffeinepills requested.
> 
> If you are still seeing leaks, it _could_ be an issue with the default audio backend (which is XAudio2 on Windows). Try manually switching to the legacy DirectSound backend to see if there is any improvement:
> 
> ```python
> import pyglet
> pyglet.options['audio'] = ('directsound', 'silent')
> 
> print(pyglet.media.get_audio_driver())     # This should show DirectSound
> ```

I can still see the leaks even when playing wave files.
The default audio audio backend as you said is indeed the XAudio2 in my case:
```
<pyglet.media.drivers.xaudio2.adaptation.XAudio2Driver object at 0x000001690C2F9C90>
```

Unfortunately even after switching the audio backend to directsound I still see the leaks allbeit a little less (Around 1MB increase for .wav files and around 2MB increase for .mp3 files) and I've confirmed this by printing the audio driver:
```
<pyglet.media.drivers.directsound.adaptation.DirectSoundDriver object at 0x000001FD02529D90>
```
If its an issue in my end please let me know.

**Comment by caffeinepills** [comment] 2023-08-17 08:48
I do see a small potential leak in WMF with the source reader.

Try adding this:

````if self._source_reader :
    self._source_reader.Release()
    ```
Somewhere in this function: https://github.com/pyglet/pyglet/blob/094c638f0529fecab4e74556487b92453a78753c/pyglet/media/codecs/wmf.py#L775

**Comment by Square789** [comment] 2023-08-18 00:31
> Great work!
> 
> > While writing this, i got the idea that the WMFDecoder may be at fault, and it likely is. I could only try wav files without it, but using the standard wav decoder didn't add any memory usage at all.
> 
> So if i'm understanding correctly, no leakage when using only `wav` files?

Yes, wav files behave just fine. I can not replicate @HauseMasterZ's problem here: https://github.com/pyglet/pyglet/issues/926#issuecomment-1681848090, wav files are loaded via the WaveDecoder which shouldn't suffer from a memory leak.



> I do see a small potential leak in WMF with the source reader.
> 
> Try adding this:
> 
> ```
> if self._source_reader:
>     self._source_reader.Release()
> ```
> 
> Somewhere in this function:
> 
> https://github.com/pyglet/pyglet/blob/094c638f0529fecab4e74556487b92453a78753c/pyglet/media/codecs/wmf.py#L775

Yeah, that was it. With [this commit](https://github.com/Square789/pyglet/commit/7a00097ff7c2ec897f38efa576a975ae54da3285), no more memory leak occurrs- Now queuing m4a, mp3, flac and whatnot is free from memory leaks as long as DirectSound is used for playback.

I have a hunch on what the issue for XAudio's continuous leaking may be. See:
```py
import ctypes
import os

class S(ctypes.Structure):
    _fields_ = (("ptr", ctypes.POINTER(ctypes.c_char)),)

x = [S() for _ in range(1_000_000)]
for s in x:
    s.ptr = ctypes.create_string_buffer(os.urandom(1024))

for s in x:
    s.ptr = None
```
After running this, python sits at ~1.6 GiB of memory usage. This ctypes-array-to-pointer assignment does not cause the pointer to take ownership of the data and is used here: https://github.com/pyglet/pyglet/blob/094c638f0529fecab4e74556487b92453a78753c/pyglet/media/drivers/xaudio2/interface.py#L302-L315
Everything assigned to pointers this way and then discarded appears to be leaked? Something i'll look into.

Since pyglet 2.0.10 is probably still at least 10 days away. I'll try fixing this, bundle all changes in the fork that don't break compatability too much to a minor-version-safe branch and then PR that.

**Comment by caffeinepills** [comment] 2023-08-18 01:14
I don't see any leaking with xaudio2 with the WMF fix.

**Comment by benmoran56** [comment] 2023-08-18 01:34
If xaudio2 is not leaking with wav files, that would seem to indicate that it's stable.  Unless WMF and XAudio2 are having some other interaction under the hood. 

Also, I can't help myself from finding micro optimizations :rofl: 
```py
data = (ctypes.c_char * audio_data.length).from_buffer_copy(audio_data.data) 
```

**Comment by HauseMasterZ** [comment] 2023-09-23 10:55
Any updates?

**Comment by benmoran56** [comment] 2023-09-23 12:57
@HauseMasterZ can you try it with the latest code in the master branch, with wav files only?

**Comment by Square789** [comment] 2023-09-23 17:53
Sorry about the excruciatingly slow progress.
The issue is long fixed in the media rewrite branch i linked before; but since i am basically just running in circles over the entire backend for the past month, getting this out into a PR early-on would have dragged in some more changes and probably become obsolete in a week again.
My time estimates always turn out horribly optimistic, but i should definitely be in the final 80% by now. I have not forgotten this issue and i do want to see it closed as much as anyone else

**Comment by HauseMasterZ** [comment] 2023-09-28 15:02
> @HauseMasterZ can you try it with the latest code in the master branch, with wav files only?

I cloned the repository, compiled the module, and tested WAV files, and it seems like the issue has been resolved! There is still a slight increase in RAM usage (around 0.2 MB), but it returns to normal after some time, so it's not an issue at all.

**Comment by Square789** [comment] 2023-10-04 00:31
After some dread after the leak popped up again i realized it is just a Python bug.
The leak can be observed on 3.11.0, but not on 3.11.6 nor 3.8.10; though i didn't test other versions and can also not deduce what the fix may be from Python's changelog.
(Also, i should probably add that my previous comment from the pointer assignment leaking is complete bogus, sorry about that)

**Comment by pushfoo** [comment] 2023-10-04 00:54
If it's only a specific range of Python 3.11 releases, the most we need to do is recommend avoiding them in the doc. Also, [3.12's first stable release just came out yesterday](https://www.python.org/downloads/release/python-3120/). We should make sure the issue doesn't occur with it.

**Comment by benmoran56** [comment] 2023-10-04 10:14
Thanks for testing this further, Square.

Let's open a new ticket for Python 3.12 to track any issues. 

Since HauseMasterZ has confirmed things are OK on their end, let's close this ticket.

**Closed by benmoran56** 2023-10-04 10:14 UTC
Labels: bug, windows, reproducible
