### ISSUE TITLE
Constant random 0x1281 OpenGL errors in multiwindow app

### ISSUE THREAD

**Issue by CORRUPTOR2037** [pyglet/pyglet#907] opened 2023-07-30 08:27 UTC
I am trying to create multiwindow app. One for main interface, one for setting window, one for context menu window and so on. Some windows (especially context menu) should be able to be closed and reopen again when requested. Right after opening another window I get error from various objects trying to be drawn on screen inside window.on_draw method.
I made sure to initialize all resources related to the window after that window's constructor is called. 

### Error log
```
  self.text.draw()
  self._batch.draw_subset(self._vertex_lists)
File "...\pyglet\graphics\__init__.py", line 463, in draw_subset
  visit(group)
File "...\pyglet\graphics\__init__.py", line 448, in visit
  alist.draw(mode)
File "...\pyglet\graphics\vertexdomain.py", line 241, in draw
  self.domain.draw_subset(mode, self)
File "...\pyglet\graphics\vertexdomain.py", line 456, in draw_subset
  self.vao.bind()
File "...\pyglet\graphics\vertexarray.py", line 23, in bind
  glBindVertexArray(self._id)
File "...\pyglet\gl\lib.py", line 79, in errcheck
  raise GLException(f'(0x{error}): {msg}')
pyglet.gl.lib.GLException: (0x1282): Invalid operation. The specified operation is not allowed in the current state.
```

### System Information

```
Platform
------------------------------------------------------------------------------
platform:  Windows-10-10.0.19045-SP0
release:   10
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
sys.maxint: 9223372036854775807

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.9
pyglet.compat_platform: win32
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False
pyglet.options['osx_alt_loop'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x000001B86F5D4C40>
screens[0]: Win32Screen(x=0, y=0, width=1920, height=1080)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 4
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: Win32ARBContext(id=1891646603520, share=Win32Context(id=1891653998896, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): NVIDIA Corporation
gl_info.get_renderer(): NVIDIA GeForce RTX 3060/PCIe/SSE2

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.xaudio2.adaptation.XAudio2Driver object at 0x000001B86F6144F0>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'openal32', handle 10000000 at 0x1b875b097e0>
Version: 1.1
Extensions:
   ALC_ENUMERATE_ALL_EXT
   ALC_ENUMERATION_EXT
   ALC_EXT_CAPTURE
   ALC_EXT_EFX

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

### How To Reproduce
I was able to create minimal required code for reproducable result. Error could be risen up after 5-th or 10-th or 30-th call but it always arise in several seconds.

```
import pyglet
from pyglet.gui.widgets import PushButton

context_menu_width = 150
context_menu_item_height = 30
image = pyglet.image.create(context_menu_width, context_menu_item_height, pyglet.image.SolidColorImagePattern((200,200,200,255)))

class Button(PushButton):
    def __init__(self, name, y):
        super().__init__(0, y, image, image)
        self.text = pyglet.text.Label(name, batch=self._batch, group=self._bg_group)
        
    def draw(self):
        self._sprite.draw()
        self.text.draw()


class ContextMenuWindow(pyglet.window.Window):
    def __init__(window):
        super().__init__(width=context_menu_width, height=context_menu_item_height)

        window.widgets = [ Button("Item", 0) ]

    def on_draw(window):
        window.clear()
        for widget in window.widgets:
            widget.draw()


window = ContextMenuWindow()

def recreate_window(x):
    global window
    window.dispatch_pending_events()
    window.close()
        
    window = ContextMenuWindow()

class MainLoop(pyglet.app.EventLoop):
    def __init__(self):
        super().__init__()

    def on_window_close(self, window):
        pass

pyglet.app.event_loop = MainLoop()
pyglet.app.event_loop.clock.schedule_interval(recreate_window, 0.2)
pyglet.app.run()
```

**Comment by caffeinepills** [comment] 2023-08-03 22:42
OpenGL 3.3 is very picky about window creation with resources. 

You will need to have both Windows created before you create any resources. Create both Windows, then make your labels and widgets after.

Closing a Window is typically not advised unless you are completely done with it, as then you will not be able to create a new window after a resource has been created. You should create the maximum number of Windows your application will need. You can then decide to hide and show them when necessary.

If you move to pyglet 1.5, the restrictions are more lenient in very old OpenGL versions, however you will have no shader support there.

**Comment by CORRUPTOR2037** [comment] 2023-08-04 04:16
switch_to() does not help in the case above.
Didn't know hiding a window was a thing, it works perfectly and definitely what I needed in case for context menu.

Also I have a case where I have a window and I want it to be resizable only when user is requested it (like, he changed it's status to resizable, resized it and locked it to unresizable again). Should I recreate my window or I can change it's status without recreation, what is recommended? Or should I create two identical windows except resizability, one is hidden by default and they share the same resources between each other?

**Comment by matanster** [comment] 2023-08-05 19:02
@CORRUPTOR2037 to your last question, [it seems by the docs location here](https://pyglet.readthedocs.io/en/latest/modules/window.html#pyglet.window.Window.resizeable) (and you can try fiddling the Window object to verify) that changing this property after creating the window is _not_ possible.

I'm not sure about the issue with avoiding to close and reopen windows, perhaps someone can elaborate on how this limitation comes into play as it's not familiar to me from using other mutli-window applications (they do create windows arbitrarily according to user interaction, I am not aware that they pre-create them to afford some maximum number of windows)

**Comment by caffeinepills** [comment] 2023-08-05 22:18
> I'm not sure about the issue with avoiding to close and reopen windows, perhaps someone can elaborate a little more on what this general limitation precisely stems from?

It varies by drivers. For instance, with Intel drivers in Windows with OpenGL 3.3, when you generate a buffer, you cannot create a shared context after. In other words you need all windows created before you make anything, otherwise creating a Window later on will error out. AMD/NVIDIA seem to be fine with it depending on driver and config, but it's not guaranteed and in all situations. VAOs also cannot be shared between contexts.

**Comment by matanster** [comment] 2023-08-06 14:35
Thanks, I can easily refactor my application to create its multiple windows on startup, but then if the user closes a window, which we can't prevent them from doing (or can we?) then it seems that the application is at a dead end if it needs to start it again and we're out of unused pre-created windows. 

It's reasonable in my application that the user would close a window and proceed with the other ones, and then expect the same window as the one they have closed, to appear again at a later point.

It the memory cost of allocating many windows upon startup in any way negligible? 

I had never realized this limitation as a desktop user before.

**Comment by matanster** [comment] 2023-08-06 14:55
It seems that we can fake and avoid closing the window:

```python
       def on_close():
            # TBD: set the window invisible, unregister its events
            # and then avoid it from closing:
            return pyglet.event.EVENT_HANDLED
```

Is that the canonical design for multi-window applications out there?
I was never aware of this limitation in general context of desktop applications before to be honest.

**Comment by caffeinepills** [comment] 2023-08-06 16:03
I believe the other way is to not have any context sharing at all between windows. However, I am not 100% sure on the consequences, pros, or cons of that. Multiple Windows could probably use a refactor since changing to OpenGL 3.3, as the current system was designed based on the OpenGL 2.x. If you need more Windowing freedom, then pyglet 1.5 may be preferable (provided you don't need shaders).

**Comment by matanster** [comment] 2023-08-06 16:41
Thank you very much. 

I think I have no issue with the new refactor based on the above, in which the window never closes. It seems well behaved in all circumstances according to my initial testing after refactoring towards that design, while also circumventing https://github.com/pyglet/pyglet/issues/911, and I'd surely not go back to pyglet 1.5.

As an aside I only notice, in the overall context of a multi window app, that many pyglet methods of a `Window` can handle the wrong window if `switch_to` is not carefully used to set the OpenGL context to the right window ― not only methods you'd expect to draw. So I guess any updated multi-window application guidelines may use broader language when describing it, but I should make a reproducible list for that. 

Should I be concerned about context sharing in the context of only using the high-level subset of pyglet drawing api? [I understand from here that context sharing is happening under the hood when using pyglet api](https://pyglet.readthedocs.io/en/latest/programming_guide/context.html#sharing-objects-between-contexts), but also something that one can introduce if they directly use the more direct OpenGL addressing parts of the pyglet api. 

Thanks for all the attention, I will put the new design to the longer test of time ― possibly coming back to make a pull request to the multi-window example code to reflect it all if it seems conclusive.

**Comment by caffeinepills** [comment] 2024-02-16 19:51
Closing as this is stale and went off topic. If the issue still persists, re-open.

However, the context issue stated in this thread should have been resolved in https://github.com/pyglet/pyglet/pull/917

**Closed by caffeinepills** 2024-02-16 19:51 UTC
Labels: bug

**Comment by matanox** [comment] 2024-12-28 11:57
Apologies, I am not sure which parts were the off-topic ones and how https://github.com/pyglet/pyglet/pull/917 is the place for follow-up discussion about it. I've mentally revisited this facet and searched for more suited tickets, the current one does mention `Window.switch_to` early on and it's mandatory for the current issue and scenario as I know it at least.

I would like to re-raise it as a question please ― 

Currently, in a multi-window application, one has to make sure to call `switch_to` before preparing objects for drawing or changing their attirbutes. This is simple in simple applications but gets more involved inapplications drawing from both timed callbacks and keyboard / mouse triggered callbacks, esp. whereby the user interaction triggered callbacks may arise in either window of the bunch. Does it make sense to abstract over this anywhere in efficient native (C/C++) code in pyglet, such that an application doesn't need to explicitly call `switch_to`? Sorry to ask it, just when going through code refactors or adding features to an already large and involved application, it may get a tad slippery to judiciously place those calls such that they cover all cases.

To reiterate, the complexity arises from having multiple callbacks manage multiple windows, some of which are user triggered and some running on an event loop cadence. The challenge for application maintenance is that a missing call (to `switch_to`) would cause a crash that won't always pop up so soon in testing since there are sometimes too many combinations of the order of callbacks given user interaction and event loop cadence scheduling, making it not as obvious to reason about where was the missing `switch_to` not placed in a large application catering for a lot of features. It makes it a little hard to ship with confidence. 

As a case in point, my application already has 20+ occurences of calling `switch_to`. Sometimes when a new feature is developed, or feature changes are made, the typical error arising from the lack of such a call will raise its head and then it's a cross-cutting review of the codebase as the error doesn't pop up locally to where the call is missing. Since it's also not deterministic, the error is not local in time to the time of the very last code change. This is very challenging for maintaining and evolving a heavy-weight application. 

I'm assuming here that calls to `switch_to` are not performance-wise trivial on some of the supported platforms.

Apologies again for re-raising this facet, or any mistakes or errors in how I have framed it.
