### ISSUE TITLE
directsound and xaudio2 audio drivers on Windows respond to volume differently

### ISSUE THREAD

**Issue by SirGnip** [pyglet/pyglet#321] opened 2020-12-03 23:49 UTC
It sounds like the `directsound` and `xaudio2` audio drivers treat the `.volume` member on the `Player` differently.

Run the script below with `xaudio2` as the driver and press the keys in order (ex: Q, W, E, R, T, Y).  You should hear beeps that get gradually quieter.  The "Y" key is silent.

Then, comment out the `xaudio2` line and uncomment the `directsound` driver.  Press the keys again in order.  You will hear beeps that are pretty much at full loudness.  Except, when you press "Y", you will hear a quiet beep.

I'd expect the volume "ramp" to be identical, regardless of what audio driver was chosen.

My environment:
- Python 3.8.6
- Pyglet: 1.5.11
- OS: WIndows 10 Home (1909)

```
import pyglet
pyglet.options["audio"] = ("xaudio2",)
# pyglet.options["audio"] = ("directsound",)

class VolumeTest(pyglet.window.Window):
    def __init__(self):
        super(VolumeTest, self).__init__()
        self.sound = pyglet.media.StaticSource(pyglet.media.synthesis.Sine(0.3, frequency=440))
        self.player = None

    def on_key_press(self, symbol, modifiers):
        if symbol == pyglet.window.key.Q:
            self.player = self.sound.play()
            self.player.volume = 1.0
        if symbol == pyglet.window.key.W:
            self.player = self.sound.play()
            self.player.volume = 0.75
        if symbol == pyglet.window.key.E:
            self.player = self.sound.play()
            self.player.volume = 0.5
        if symbol == pyglet.window.key.R:
            self.player = self.sound.play()
            self.player.volume = 0.25
        if symbol == pyglet.window.key.T:
            self.player = self.sound.play()
            self.player.volume = 0.1
        if symbol == pyglet.window.key.Y:
            self.player = self.sound.play()
            self.player.volume = 0.0001

if __name__ == '__main__':
    print(pyglet.media.get_audio_driver())
    window = VolumeTest()
    pyglet.app.run()
```

**Comment by benmoran56** [comment] 2020-12-04 07:55
Thanks for opening the ticket.

This looks like a bug in the DirectAudio backend, since a linear adjustment is expected. 
It looks like the culprit is this function here: https://github.com/pyglet/pyglet/blob/master/pyglet/media/drivers/directsound/adaptation.py#L54

I'm not an expert on this, but switching from math.log10 to math.log2 _does_ seem to give the expected result. If possible, are you able to test this on your machine as well?

You _might_ be able to do a quick monkey-patch like this: 

```py
import math
import pyglet
import pyglet.media.drivers.directsound

pyglet.options["audio"] = ("directsound", "silent")


def my_gain2db(gain):
    if gain <= 0:
        return -10000
    return max(-10000, min(int(1000 * math.log2(min(gain, 1))), 0))

pyglet.media.drivers.directsound.adaptation._gain2db = my_gain2db
```

**Comment by SirGnip** [comment] 2020-12-04 13:59
I did the monkey patch.  It brought the volume ramps closer together.  Now I'm no audiophile, but I still hear a volume difference between the two drivers.  

"A picture is worth a thousand listens", so I recorded myself playing Q, W, E, R, T and then Q & T again in Audacity for each driver (had Audacity record from the "Windows WASAPI" audio host). The waveforms were generated by these drivers, in order:
- xaudio2
- directsound
- directsound with monkey-patch

![image](https://user-images.githubusercontent.com/5678175/101171149-fef26680-3604-11eb-88c4-f4437fff9468.png)

FWIW, the "directsound with monkey-patch" code sounds most "pleasing" to the ear (a linear decay in volume values results in a linear decay of perceived volume).

(I am also a bit curious about the slow volume "swell" seen on each note in all drivers... but maybe that is for another ticket...)

**Comment by caffeinepills** [comment] 2020-12-04 16:04
XAudio2 is based on amplitude values while DirectSound is 100ths of a decibel. Not entirely sure if a 1:1 will be possible, but it might be close enough. I am not sure I am one to judge which sounds most 'proper'.

With XAudio2 it doesn't adjust for anything outside of what you pass to it. (Thinking on it, should probably put some clamp values to it just for sanity sake.)

The swell may be because the play is done before adjusting the volume, therefore you may get some small period where the volume has not been adjusted yet. I am not sure why the swell with XAudio2 is larger (if it's the first two). A theory I have is that XAudio2 probably starts quicker since it's sent to the hardware, whereas DirectSound is software emulated.

You may have better luck creating a `pyglet.media.Player()`, storing it so it doesn't get GC'd, setting the volume of it, then queueing and playing the source so that the volume is set prior to playback.

Perhaps a minor enhancement in the future would be an optional keyword to adjust volume when calling play, so such a workaround is not needed for throwaway players.

**Comment by SirGnip** [comment] 2020-12-04 23:41
Thanks for clarification on the 100ths of a decibel vs amplitude.  Helpful.  So, it sounds like volume levels are specific to audio drivers meaning that if an app need a repeatable volume level, it needs to "pin" itself to a specific driver... Or, the app would need to do some kind of mapping function that attempts to normalize volume levels based on which driver is active? Sounds like work.  :)

Regarding the swell, I did another test.  First I first ran my test script (above) with XAudio2 and recorded the waveform.  Then, I changed the script so that it did the "create Player first" approach (code snippet below) and ran it (again, with XAudio2) and recorded the waveform.

```
self.player = pyglet.media.Player()
self.player.volume = 1.0
self.player.queue(self.sound)
self.player.play()
```
The swells were still there and nearly identical between the two approaches (the two recordings were done in mono):

![image](https://user-images.githubusercontent.com/5678175/101225758-e65f6c00-3657-11eb-9ac5-fc91b449f3c5.png)

I'd 👍 adding a volume parameter to `Source.play`.  I think `pitch` could be another good one to add.

**Comment by benmoran56** [comment] 2020-12-05 14:11
Just a quick hunch @SirGnip, but since that didn't work, what happens if you create a waveform that's not maximum amplitude?

```py
envelope = pyglet.media.synthesis.FlatEnvelope(amplitude=0.8)
sound = pyglet.media.synthesis.Sine(1, envelope=envelope)
```
By default the waveforms are created with maximum amplitude, which could potentially be overdriven.

**Comment by benmoran56** [comment] 2020-12-05 14:19
On a related note, if these tones are for human ears, you probably will want to do an ADSR envelope to make it more pleasant to listen to. Otherwise you'll get popping/clicking artifacts when playback starts/stops. This is caused by the waveform abruptly starting/stopping at a value that's likely far from neutral. (My apologies if you already know this, but just figured I'd mention).  For example: 

```py
envelope = pyglet.media.synthesis.ADSREnvelope(attack=0.05, decay=0.1, sustain_amplitude=0.6, release=0.1)
sound = pyglet.media.synthesis.Sine(1, envelope=envelope)
```

**Comment by SirGnip** [comment] 2020-12-05 14:51
Yup, I'm familiar with envelopes.   Just keeping the repro cases minimal.

I did just add the `FlatEnvelope` to my "create Player object first" script and used XAudio2

envelope = pyglet.media.synthesis.FlatEnvelope(amplitude=0.5)
self.sound = pyglet.media.StaticSource(pyglet.media.synthesis.Sine(0.3, frequency=440, envelope=envelope))

...and reran the "test".  Still can see the pop at the start and then a swell in the tail:
![image](https://user-images.githubusercontent.com/5678175/101245913-a63ece80-36d5-11eb-8546-f430aa0d1451.png)

Also, I tried this:
`envelope = pyglet.media.synthesis.LinearDecayEnvelope()`
...and got this:

![image](https://user-images.githubusercontent.com/5678175/101246001-1e0cf900-36d6-11eb-81eb-045ad76afbf7.png)

You can certainly see the envelope fading the amplitude as expected, but with pops at the beginning.

I also tried the envelopes with the DirectSound driver.  The initial pops were still there, but slightly less pronounced.

**Comment by caffeinepills** [comment] 2020-12-05 21:45
Is this pop at the beginning only happening with synthesis? Any issues with other sources? Also do different amplitudes or frequencies affect it?

**Comment by SirGnip** [comment] 2020-12-06 14:46
(TL;DR post... the pops, swells, and odd enveloping behavior is interesting to me as I'm working on using `pyglet.media.synthesis` for creating music.  So, treatment of Pyglet's synthesizers, volume levels and enveloping is very interesting to me...)

I ran my test script (that uses the "create Player object first") through a number of different scenarios.  Each time I played the 5 notes with descending volume settings.  I would do the two scenarios and then screenshotted the waveforms.  The first five beeps are from the first config and the last 5 beeps are from the second config.

**Executive summary**:
Initial pops are seen with:
* XAudio2 and DirectSound audio drivers
* audio loaded from .wav files
* audio generated from synthesis objects (Sine, Square and Triangle) at different frequencies
* FlatEnvelope with different amplitudes
* LinearDecayEnvelope (but less pronounced pops)

Initial pops are NOT seen with `ADSREnvelope`.  But, there was other weird amplitude behavior observed with ADSR envelopes, mentioned below.

----------

1 - Pyglet synthesis for a 440 sine wave, XAudio2 driver with 3D enabled **versus** 3D disabled:
![image](https://user-images.githubusercontent.com/5678175/101281808-f92c8a80-3796-11eb-8544-c24c60204f44.png)

----------

2 - Pyglet syntheses for a 440 sine wave, DirectSound driver:
![image](https://user-images.githubusercontent.com/5678175/101281858-3729ae80-3797-11eb-9092-f0ad299162ed.png)

----------

3 - XAudio2 driver with 3D disabled, a synthesis 440 sine wave **vs** a .wav file generated by Audacity (440 Hz sine wave, 0.5 seconds long at 1.0 amplitude)
`pyglet.media.StaticSource(pyglet.media.synthesis.Sine(0.5, frequency=440, envelope=envelope))`
**versus**
`self.sound = pyglet.media.load("resources/audio/SampledSine_440_1.0.wav", streaming=False)`
![image](https://user-images.githubusercontent.com/5678175/101281904-78ba5980-3797-11eb-856d-5b6aa944a976.png)

----------

4 - XAudio2 driver with 3D disabled, a synthesis 440 Hz sine wave **versus** a synthesis 261.63 Hz sine wave
![image](https://user-images.githubusercontent.com/5678175/101281968-e2d2fe80-3797-11eb-9bdd-8252afdc191d.png)

----------

5 - XAudio2 driver with 3D disabled, a synthesis 440 Hz sine wave with different envelopes
`pyglet.media.synthesis.FlatEnvelope(amplitude=1.0)`
**versus**
`pyglet.media.synthesis.FlatEnvelope(amplitude=0.5)`

![image](https://user-images.githubusercontent.com/5678175/101282058-5a089280-3798-11eb-8d1a-f8d63c544516.png)

----------

6 - XAudio2 driver with 3D disabled, a 440 Hz sine wave with `LinearDecayEnvelope`
(pops are there, but not as pronounced)
![image](https://user-images.githubusercontent.com/5678175/101283296-0c435880-379f-11eb-91ec-63f7c1732c5d.png)

----------

7 - XAudio2 driver with 3D disabled, a synthesis 440 Hz sine wave with duration of 1.0 with FlatEnvelope vs ADSR envelope (with slow-ish attack):
`pyglet.media.synthesis.FlatEnvelope(amplitude=1.0)`
**versus**
`pyglet.media.synthesis.ADSREnvelope(0.2, 0.2, 0.2)`
The results for this one are interesting.  I don't see any initial pops with the ADSR envelope.  But, a couple odd things.  First, I'd expect to see a portion of the waveform having a "flat" or "steady" amplitude during the "sustain" portion of the envelope (see ascii-art).  
```
  /\
 /  \___
/       \
```
But, looking at the 4th and 5th "beeps" that use the ADSR, you can see the "sustain" portion of the sound is actually increasing in volume over time by looking at the waveform below.
Second issue... I see the ADSR envelope having very little affect on 1st and 2nd beeps.  For instance, the attack is set at "0.2" but zooming into the 1st beep, the time to go from silence to full amplitude is about 0.04 seconds.  And, I don't see any decay or sustain.  Just the too-quick attack at the start and a too-quick decay at the end. Probably some kind of clipping/overdrive beyond the 1.0 amplitude?
![image](https://user-images.githubusercontent.com/5678175/101282140-e0bd6f80-3798-11eb-9e84-1850e73fa454.png)

----------

8 - XAudio2 driver with 3D disabled, a no-envelope synthesis 440 Hz square **versus** a synthesis 440 Hz triangle
![image](https://user-images.githubusercontent.com/5678175/101282777-9b9b3c80-379c-11eb-8633-dcddac931646.png)

----------

9 - XAudio 2 driver with 3D disabled, using a 1.0 second long, 440 Hz triangle wave. 
pyglet.media.synthesis.FlatEnvelope(amplitude=1.0)
**versus**
pyglet.media.synthesis.ADSREnvelope(0.2, 0.2, 0.2)
The 4th and 5th beeps that use the ADSR envelope show the expected envelope shape.  However, the 1 & 2nd beeps show the ADSR having very little affect.  Again, with `.volume=1.0` and `.volume=0.75` set on the Player, I would expect those amplitude levels to be the "max" amplitude of the envelope that happens right at the end of the attack part of the envelope.  It is worth noting that there is no distortion in the waveform for those first two beeps with ADSR.  It is just the amplitude that appears clipped.
![image](https://user-images.githubusercontent.com/5678175/101282897-372cad00-379d-11eb-94c8-8fb2ae391526.png)

**Comment by benmoran56** [comment] 2020-12-10 07:04
Sorry for the delay. 
I spun up my Windows VM, and tried to replicate your results. 
First of all, I **am** seeing the "pop" with the XAudio2 driver. With the DirectAudio, it's completely smooth. I have not yet tried with 3D disabled, so I will try that later. 

In both cases, however, I've been completely unable to replicate the issues with the volume "swelling". I tried all of the different recording sources in Audacity with no change. It also seems like my overall volume in Audacity is lower, but I was unable to figure out why the difference. Looking at your screen shots again, it looks like there might possibly be some type of dynamic volume adjustment or compression applied. Maybe a feature of the sound card? 

![Screenshot from 2020-12-07 10-30-16](https://user-images.githubusercontent.com/1715390/101732786-1b106f00-3b01-11eb-8fcc-8ab973b7b92c.png)

**Comment by SirGnip** [comment] 2020-12-10 14:17
To start to prove the sound card "feature" theory, I flipped my audio output from "headphones" to "USB headset".  After I did that and repeated the ADSR test, I got results that looked like yours (nice, crisp ADSR envelope shapes).  Shazam...

So, I flipped back to "headphones" and started poking around in the innards of  WIndow's sound settings.  I found "Disable all sound effects" and also "Dolby Audio".  I turned both of those off and repeated my test.  Crisp ADSR envelopes.  Smoking gun.  My laptop's build in sound card was "helping" me by applying compression and goodness knows what else.

After turning those settings off, things were a bit quieter, volume ramps were much more in line with what I would expect, no swells, were gone, etc.  As you said, "Dolby Audio" must be a compressor (among other things...)

Now that we figured that out, I was able to go back and redo some of the earlier tests (without all this extra "help" from Dolby).  The initial pops appear when 3D is ON with the XAudio driver. But, when I turn 3D off, the initial pops disappear.

So with enhancements off, Dolby off, and XAudio 3D off, I get very crisp, clean waveforms and envelopes with no initial pops.

I also tried DirectSound and also got very crisp, clean waveforms with no pops (though the volume was lower).

So, now that the compressor is out of the way, I went back to the original issue (volume difference between drivers) and reran the test to compare volume output between XAudio2 and DirectSound

The waveforms below are recorded from three different tests (with "enhancements" off...)
* 5 beeps with XAudio2 no 3D
* 5 beeps with DirectSound
* 5 beeps with DirectSound with monkey patched _gain2db
![image](https://user-images.githubusercontent.com/5678175/101782344-808f3c00-3abe-11eb-881b-ede1c80f72ab.png)

The monkey patching does seem to get the volume ramp to be more what I would expect.  Also, DirectSound looks quieter than XAudio2 in general.  After my adventures with audio drivers, though, chances are the volume differences is probably just some local volume setting I have.

So, thanks for your time and patience, @benmoran56, in helping me find the "Turn off Dolby" button.  :)

**Comment by benmoran56** [comment] 2020-12-15 13:52
Sorry for the delay, but I just wanted to add that I could not see any volume difference between Xaudio and DirectAudio on my Windows VM, so it may also be sound card driver specific (as you suspect). 

I'm not sure if it's worth fooling around with the gain functions in the DirectAudio driver or not, considering it's deprecated.  I think instead, we can just try to work out a solution for the Xaudio2 3D setting since that's the default.

**Comment by benmoran56** [comment] 2021-06-06 05:46
After some thought, I went ahead and pushed the gain2db function change in for consistency. 
I'll close this for now, but look for that in the next point release.

**Closed by benmoran56** 2021-06-06 05:46 UTC
