### ISSUE TITLE
Memory leak with pyglet 1.5.2 and 1.5.1 when used with pymunk (1.5.0 works fine)

### ISSUE THREAD

**Issue by viblo** [pyglet/pyglet#178] opened 2020-03-29 18:50 UTC
Got a report here https://github.com/viblo/pymunk/issues/176 from one of the users of Pymunk of a memory issue when using the Pymunk drawing code for pyglet (growing memory usage with 10s of megabytes in just a minute).

I did a bit of testing and it shows that Pyglet up to 1.5.0 works fine (tested 1.4.1 and 1.4.10 as well), while Pyglet 1.5.1 and 1.5.2 does not, so I guess there's some memory leak in there (unless the pymunk code does something strange to draw ofc)

**Comment by benmoran56** [comment] 2020-03-30 10:12
Thanks for opening the ticket. I was able to confirm this on my machine, and tracked down the cause. I'll try to get a fix in soon.

**Comment by benmoran56** [comment] 2020-03-30 14:04
This *should* be fixed in the `pyglet-1.5-maintenance` branch. If possible, could you give it a try and let me know if you still have issues? 
It turns out that after a small performance improvement that went into 1.5.1, an unintended side affect was that we were failing to free dead textures. Your example seems to be creating/deleting new textures each frame, causing the usage to continuously rise.

**Comment by viblo** [comment] 2020-03-30 18:42
Thanks for the quick fix. Works fine with the maintenance branch. 
The code is only drawing primitives like GL_TRIANGLE_STRIP, but maybe they will result in new textures underneath.

**Comment by caffeinepills** [comment] 2020-03-30 21:12
The cleanup involves both textures and buffers. I may be way off here as I am just having a brief look at pymunk's drawing, but there might be issues with the way you draw things:

pymunk/pyglet_util.py
```
    def __enter__(self):
        if self.new_batch:
            self.batch = pyglet.graphics.Batch()
    def __exit__(self, type, value, traceback):
        if self.new_batch:
            self.batch.draw()
```

Looking at this code, if you are letting pymunk control the batching, it seems to me everytime `__enter__` is called you create a new batch, which would mean the old one becomes stale and garbage collected. Which would also mean you are adding the vertex data every frame as well. This is terribly inefficient and probably why this showed the issue more than most.

**Comment by viblo** [comment] 2020-04-02 19:28
Yes, its a side effect of how the drawing works. Pymunk is using a C-library called Chipmunk for its physics simulations, and also uses callbacks provided by Chipmunk for drawing. So each frame Pymunk has a couple of functions for drawing primitives, like draw_circle(), which is called from the C-code in callbacks. There is no state between frames in these callbacks, so Pymunk creates a new batch (or if you provide your own you must clear it) since it cant keep track of if a triangle strip (or other drawing) already exists very easily.

But I fully agree, it is not the most optimal way to draw things :) This draw feature is mainly meant for quick prototyping and/or debugging, so as long as it reasonably performant its ok. At the same time Im very open to suggestions on how to improve it.

**Comment by benmoran56** [comment] 2020-04-03 04:30
If no state is kept, and it's not possible to keep it,  it would be better to draw using `pyglet.graphics.draw`. This is not very efficient, but it's probably a bit faster than creating a new Batch every time.

**Comment by viblo** [comment] 2020-04-04 18:54
Are you sure? I tested to examples I had and when I replaced the calls to `batch.add` with `graphics.draw` the fps was reduced by (very roughly) 50%.

**Comment by benmoran56** [comment] 2020-04-06 01:27
I haven't looked into your code very far, so my apologies, but it *should* be faster if you're just drawing a single object each time. If you're adding more than one thing to the temporary batch, then it could be faster.

**Comment by benmoran56** [comment] 2020-04-06 07:32
I just pushed out pyglet 1.5.3, which includes the fix. It's available for download here and PyPI. 
This should get things back to normal!

**Comment by viblo** [comment] 2020-04-07 18:38
Thanks! The latest version works fine.

**Comment by benmoran56** [comment] 2020-04-08 00:53
Great. I'll close this for now then. Thanks again for opening the ticket!

**Closed by benmoran56** 2020-04-08 00:53 UTC
