### ISSUE TITLE
Input text doesn't work on Mac

### ISSUE THREAD

**Issue by LPitonakova** [pyglet/pyglet#350] opened 2021-02-05 15:24 UTC
I am on MacOS 11.1 and trying the example in examples/gui/widgets.py. I installed pyglet 1..5.14  via pip in a virtual environment. The input text doesn't seem to work correctly - sometimes it reacts to my keyboard, sometimes it doesn't. E.g. I select the whole text to try to rewrite it, but that doesn't work. When I simply click into the text and delete it first, then type a new one, that sometimes works and sometimes not.

**Comment by benmoran56** [comment] 2021-02-06 00:19
Hi, 

Could you try this example, and see if it works as expected?
https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/text/text_input.py

**Comment by jmp** [comment] 2021-06-20 09:23
@benmoran56

I'm on macOS 11.4 (and `pyglet-1.5-maintenance` checked out from GitHub) and I can confirm the same problem here.

In `examples/text/text_input.py`, I'm unable to input any text into text fields - or at least no text appears on the text fields themselves.

In `examples/gui/widgets.py`, the I can see that the text field seems to work but it doesn't seem to render correctly:
* After opening the example, the text field is empty and the label next to it says "Text: None"
* If I click the text field once and press enter, the text field stays empty but the label changes to "Text: Enter Your Name"
* If I then click the text field once, then hit backspace until it should be empty, type "Test" (blindly, since the text field stays empty all this time) and hit enter, the text field is still empty but the label changes to "Text: Test".

So it appears as if text field appears to know what text it contains but it just doesn't seem render it.

**Comment by carey-bunks** [comment] 2022-08-03 09:05
I'm having the same problem on MacOS 12.5 on a MacBook Pro with an M1 chip.  My version of pyglet is 1.5.26.  Any solutions to this would be well appreciated!

**Comment by benmoran56** [comment] 2022-08-04 23:55
Unfortunately we're currently lacking anyone with M1 hardware to look into this.
Can you check with the latest code from the master branch, and see if that behaves any different?

**Comment by caffeinepills** [comment] 2023-03-15 18:56
This should be resolved in master branch.

**Closed by caffeinepills** 2023-03-15 18:56 UTC
