### ISSUE TITLE
Some EventDispatchers can't dispatch some events

### ISSUE THREAD

**Issue by zhengxyz123** [pyglet/pyglet#418] opened 2021-07-15 03:18 UTC
> According to [this issue](https://github.com/Minecraft-in-python/Minecraft/issues/22).

I use `EventDispatcher` to make GUI in the game. **Some** GUIs run well, **others** can receive `on_mouse_motion` but they can't receive `on_mouse_press` event. It's very strange!

**Comment by benmoran56** [comment] 2021-07-15 07:13
Can you post some example code?

**Comment by jason-bowen-zheng** [comment] 2021-07-15 07:56
That's not a good idea. It's a whole game. Every parts work together.

- [GUI widget](https://github.com/Minecraft-in-python/Minecraft/blob/master/minecraft/gui/widget/base.py)
- [Where the issue happened](https://github.com/Minecraft-in-python/Minecraft/blob/master/minecraft/gui/widget/slot.py)

**Comment by benmoran56** [comment] 2021-07-15 08:07
I can't tell anything from your code, because it does not show the handler pushing. 

Make sure that you are using `Window.push_handlers`. Otherwise, you might be replacing a handler, instead of adding it.

**Comment by jason-bowen-zheng** [comment] 2021-07-15 08:46
[The GUI frame with handler like pyglet.gui.frame.Frame](https://github.com/Minecraft-in-python/Minecraft/blob/master/minecraft/gui/frame.py)

It's ***some***, not ***all***.

**Comment by benmoran56** [comment] 2021-07-16 05:43
Can you make a small example, that shows the issue? I can't replicate it.

**Comment by jason-bowen-zheng** [comment] 2021-07-16 07:39
Small example with code? I can't. It's a big project. I just know some GUI widgets can receive `on_mouse_motion` event but can't receive `on_mouse_press` event.

**Comment by caffeinepills** [comment] 2021-07-16 19:14
Can't reproduce this either. This is most likely an issue with your hit detection or ordering of event handle returns. It's impossible to say without looking at a simple runnable example.

**Comment by jason-bowen-zheng** [comment] 2021-07-16 22:28
I found some code, this issue maybe solve part:
```python
# method in Frame class
def on_mouse_press(self, x, y, buttons, modifiers):
    if not self._enable:
        return
    for widget in self._widget:
        widget.dispatch_event('on_mouse_press', x, y, buttons, modifiers)
        if widget.check_hit(x, y):
            return True
```
If I remove the last 2 lines, This issue will solve.

**BUT**, the `on_mouse_press` event won't stop transmitting and the `Window` will finally dispatch this event and do something unexpected.

So, @benmoran56 can you tell me how pyglet manages GUIs  in the future?

**Comment by caffeinepills** [comment] 2021-07-17 14:25
Shouldn't you dispatch the event only when it hits?

Like this:
```
    for widget in self._widget:
        if widget.check_hit(x, y):
            widget.dispatch_event('on_mouse_press', x, y, buttons, modifiers)
            return True
```

**Comment by jason-bowen-zheng** [comment] 2021-07-17 22:09
I know my code has some problems. But, `check_hit` is unnecessary:
```python
# It's in every class which inherit EventDispatcher
def on_mouse_press(self, x, y, buttons, modifiers):
    if self.check_hit(x, y) and self._enable:
        self.dispatch_event('on_press')
```
@caffeinepills , Your way isn't the best way:
```python
# I think It shouldn't return True, just skip 'for'
if widget.check_hit(x, y):
    widget.dispatch_event('on_mouse_press', x, y, buttons, modifiers)
    return
```

**Comment by caffeinepills** [comment] 2024-09-30 23:18
Closing as it's been a long time and we couldn't reproduce. Re-open with a simple runnable example if problem persists.

**Closed by caffeinepills** 2024-09-30 23:18 UTC
