### ISSUE TITLE
 TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

### ISSUE THREAD

**Issue by eamanu** [pyglet/pyglet#137] opened 2020-01-28 23:28 UTC
During the build of pyglet on Debian unstable using Python 3.8 the tests fails.

Originally reported here [1]. Also, you can view more detail on [2]

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950039
[2] https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/pyglet.html

Cheers,

**Comment by benmoran56** [comment] 2020-01-28 23:49
Hi @eamanu, thank you for opening the ticket. This is caused by a change introduced in the latest Python releases. (Issue #112) This has already been fixed in pyglet v1.4.9, so updating the Debian package to target the latest release will be necessary to support Python 3.8.1+.

**Comment by benmoran56** [comment] 2020-03-01 01:28
Hi @eamanu I'm going to close this for now, but please reopen it if you want to follow up.

I've sent an email to the mailing list.

**Closed by benmoran56** 2020-03-01 01:28 UTC
