### ISSUE TITLE
Saving screenshots fails on Mesa Intel/AMD systems using Pyglet 2.0.0

### ISSUE THREAD

**Issue by teknohog** [pyglet/pyglet#703] opened 2022-11-10 21:02 UTC
I have used the following command from Pyglet docs to save screenshots in my application for years:

pyglet.image.get_buffer_manager().get_color_buffer().save(shotfile)

After updating to Pyglet 2.0.0, it continues to work only on my systems with Nvidia GPUs. On my Intel and AMD systems using Mesa (currently 22.2.3), the command now fails as follows:

  File "/usr/lib/python3.10/site-packages/pyglet/image/__init__.py", line 2070, in get_buffer_manager
    context.image_buffer_manager = BufferManager()
  File "/usr/lib/python3.10/site-packages/pyglet/image/__init__.py", line 1990, in __init__
    glGetFramebufferAttachmentParameteriv(
  File "/usr/lib/python3.10/site-packages/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x502): Invalid operation. The specified operation is not allowed in the current state.

This should not be a question of supported OpenGL versions. My least capable Intel system supports OpenGL 3.3 core. Besides the screenshot issue, my application runs fine otherwise, using OpenGL 3.x features such as transform feedback and geometry shaders.

**Comment by einarf** [comment] 2022-11-10 21:32
It seems to be related to a stencil buffer bits lookup:
https://github.com/pyglet/pyglet/blob/003641ab7838d7b3cff2686d3028dad9c0c4cb44/pyglet/image/__init__.py#L1989-L1996

We might be using some deprecated enums here.
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetFramebufferAttachmentParameter.xhtml

I assume `GL_STENCIL_ATTACHMENT` should be used instead in addition to a try/except if no stencil buffer is present. Optionally this stencil bits querying should just be moved to the `get_buffer_mask` method? In 99.9% of cases users won't care about stencil buffer these days.. if ever.

**Comment by benmoran56** [comment] 2022-11-14 02:18
I just confirmed this on my Linux machine, with MESA/AMD. 

Changing `GL_STENCIL`  to  `GL_STENCIL_BUFFER_BIT` _does_ fix the crash, but I'm not sure if it's supposed to :sweat_smile:.
@teknohog, if you could try that on my Nvidia machine, and make sure that it still works there, that would be very helpful.

@einarf thanks for the pointers. I've been meaning to revisit this code, but haven't had the chance yet.

**Comment by benmoran56** [comment] 2022-11-14 09:14
My earlier "fix" doesn't work consistently, so please disregard that. It always returns 0 even when it doesn't crash, so it's not really a fix. It's probably better to do as you suggested @einarf, and move that query outside of `__init__`. 

Also, I haven't yet been able to get the `glGetFramebufferAttachmentParameteriv` function to work at all on my machine. I'm fairly certain I'm following the documentation, but no success yet. Even if it doesn't crash, `stencil_bits` is always 0. I need to read up more on this, with regards to GL3.3+.

**Comment by einarf** [comment] 2022-11-14 13:35
Can it be that the default framebuffer don't have stencil bits in your case?

For the future I'm more fan of interacting with a framebuffer wrapper class ro something making it clear what is getting dumped.

**Comment by teknohog** [comment] 2022-11-14 15:48
> Can it be that the default framebuffer don't have stencil bits in your case?

I've looked at window.context.config and that certainly shows some differences: On Nvidia, it has aux_buffers = 4 and accum_{red,green,blue,alpha)_size = 16, but on Mesa Intel these are all zero. So maybe the aux buffer is used as a stencil buffer?

These are all from the default config. I've also tried setting the config to have aux_buffers = 4 but it raises a NoSuchConfigException. I can set the accum* sizes to 16 but they don't help with the original issue.

**Comment by benmoran56** [comment] 2022-11-15 06:25
If it's raising that exception, it's coming right from the driver itself.

That does help clear some things up though. I'll move the stencil check code outside of `__init__` for a start.

**Comment by benmoran56** [comment] 2022-11-16 03:44
Thanks for opening the ticket @teknohog
I'll close this for now, since I just pushed a fix to master. This will be in the next point release.

I moved the stencil buffer query logic out of `__init__`. If you try to do a `get_buffer_mask` and it fails, it will give a "no stencil buffers available" traceback.

**Closed by benmoran56** 2022-11-16 03:44 UTC
