### ISSUE TITLE
macOS: Window resize throws an exception

### ISSUE THREAD

**Issue by didiermalenfant** [pyglet/pyglet#323] opened 2020-12-07 13:06 UTC
I'm using python 3.8.2 with cocos2d v0.6.9 and pyglet 1.5.11. This is all on macOS 11.0.1.

When resizing the window, I get the following exception:
```
pyglet.gl.lib.GLException: b'invalid value'
2020-12-07 14:00:21.594 python[9105:84843] *** Assertion failure in -[NSCGSWindow setSize:], NSCGSWindow.m:1516
2020-12-07 14:00:21.596 python[9105:84843] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: size.width >= 0.0 && size.width < (CGFloat)INT_MAX - (CGFloat)INT_MIN && size.height >= 0.0 && size.height < (CGFloat)INT_MAX - (CGFloat)INT_MIN'
```
I saw an old thread in a search engine on bitbucket about this but the thread doesn't exists anymore on the site.

Apologies in advance if this is not related to pyglet, it just looks to be from my end.

**Comment by benmoran56** [comment] 2020-12-07 13:57
Does this happen any time you try to resize the window, or only when you resize to a 0 width or height?

In any case, give this pyglet-only test a try and see if you get the same result: 
```py
import pyglet

window = pyglet.window.Window(resizable=True)

@window.event
def on_draw():
    window.clear()


pyglet.app.run()
```

**Comment by didiermalenfant** [comment] 2020-12-08 08:52
Thanks for the quick reply @benmoran56.

It does look like pyglet may not be the culprit here. This small test works fine on my end.

I guess I'll start digging into what cocos2d is setting up or doing incorrectly to cause this.

**Comment by benmoran56** [comment] 2020-12-08 08:56
No worries! At least that narrows it down. Looking at the error message, it does seem to be caused by the window dimensions trying to set to 0 somewhere.
 
I'll close this for now, but if you're able to find anything else that's pyglet related, please reopen it! 
Good luck!

**Closed by benmoran56** 2020-12-08 08:56 UTC
