### ISSUE TITLE
Build document failed

### ISSUE THREAD

**Issue by jason-bowen-zheng** [pyglet/pyglet#282] opened 2020-09-30 23:53 UTC
Today I tried to build the pyglet 2.0 document, but failed:
```
$ make htmlhelp
sphinx-build -b htmlhelp -d _build/doctrees   . _build/htmlhelp
Running Sphinx v2.3.1
Generating pyglet 2.0.dev0 Documentation
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [htmlhelp]: targets for 64 source files that are out of date
updating environment: [new config] 64 added, 0 changed, 0 removed
Exception ignored in: <function Shader.__del__ at 0x7fa0311430>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self._id)
AttributeError: 'Shader' object has no attribute '_id'
Exception ignored in: <function Shader.__del__ at 0x7fa0311430>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self._id)
AttributeError: 'Shader' object has no attribute '_id'
Exception ignored in: <function Shader.__del__ at 0x7fa0311430>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self._id)
AttributeError: 'Shader' object has no attribute '_id'
Exception ignored in: <function Shader.__del__ at 0x7fa0311430>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self._id)
AttributeError: 'Shader' object has no attribute '_id'
WARNING: autodoc: failed to import module 'graphics.allocation' from module 'pyglet'; the following exception was raised:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/data/data/com.termux/files/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/__init__.py", line 818, in <module>
    _default_vert_shader = Shader(_vertex_source, 'vertex')
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 174, in __init__
    raise GLException("The {0} shader failed to compile. "
pyglet.gl.lib.GLException: The vertex shader failed to compile.
Compiled vertex shader successfully.


Exception occurred:
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 174, in __init__
    raise GLException("The {0} shader failed to compile. "
pyglet.gl.lib.GLException: The vertex shader failed to compile.
Compiled vertex shader successfully.
The full traceback has been saved in /data/data/com.termux/files/usr/tmp/sphinx-err-fkti4m_y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Exception ignored in: <function Shader.__del__ at 0x7fa0311430>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/pyglet/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self._id)
AttributeError: 'Shader' object has no attribute '_id'
make: *** [Makefile:71: htmlhelp] Error 2
```

**Comment by benmoran56** [comment] 2020-11-19 06:08
Hi, this is a duplicate of  https://github.com/pyglet/pyglet/issues/85
The documentation has not yet been updated, until the codebase stabilizes a bit more. 

I'll close this for now, but thank you for opening the ticket!

**Closed by benmoran56** 2020-11-19 06:08 UTC
