### ISSUE TITLE
Smaller rendering scale after setting Window's size

### ISSUE THREAD

**Issue by DreamAlone666** [pyglet/pyglet#785] opened 2023-03-02 10:35 UTC
**Describe the bug**
As the screenshots show, setting `Window`'s size using `width` and `height` property will cause smaller rendering scale.
The `Rectangle`'s properties have not changed..
![pgl_bug1](https://user-images.githubusercontent.com/117426615/222402726-5e2ba640-b048-4fcd-92fa-75b9bd1a664d.png)
![pgl_bug2](https://user-images.githubusercontent.com/117426615/222402783-a380c003-44a8-4360-aa02-bab6755ae6f7.png)

**System Information:**
```python
Platform
------------------------------------------------------------------------------
platform:  Windows-7-6.1.7601-SP1
release:   7
machine:   AMD64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
sys.maxint: 9223372036854775807
os.getcwd(): D:\Program Files\Temp\ecsfp

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.5
pyglet.compat_platform: win32
pyglet.__file__: d:\Program Files\python-3.8.10-embed\lib\site-packages\pyglet\__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['dw_legacy_naming'] = False
pyglet.options['win32_disable_xinput'] = False
pyglet.options['com_mta'] = False

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.win32.Win32Display object at 0x00000000032A70A0>
screens[0]: Win32Screen(x=0, y=0, width=1440, height=900)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 8
config['depth_size'] = 24
config['stencil_size'] = 8
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = 'gl'
config['debug'] = None
context: Win32ARBContext(id=41508672, share=Win32Context(id=53116688, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (3, 3)
gl_info.get_vendor(): Intel
gl_info.get_renderer(): Intel(R) HD Graphics
gl_info.get_extensions():
   GL_3DFX_texture_compression_FXT1
   GL_ARB_ES2_compatibility
   GL_ARB_ES3_compatibility
   GL_ARB_arrays_of_arrays
   GL_ARB_base_instance
   GL_ARB_blend_func_extended
   GL_ARB_buffer_storage
   GL_ARB_color_buffer_float
   GL_ARB_compressed_texture_pixel_storage
   GL_ARB_conservative_depth
   GL_ARB_copy_buffer
   GL_ARB_debug_output
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_depth_texture
   GL_ARB_draw_buffers
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_indirect
   GL_ARB_draw_instanced
   GL_ARB_explicit_attrib_location
   GL_ARB_fragment_coord_conventions
   GL_ARB_fragment_program
   GL_ARB_fragment_program_shadow
   GL_ARB_fragment_shader
   GL_ARB_framebuffer_no_attachments
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_geometry_shader4
   GL_ARB_get_program_binary
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_internalformat_query2
   GL_ARB_map_buffer_alignment
   GL_ARB_map_buffer_range
   GL_ARB_multi_draw_indirect
   GL_ARB_multisample
   GL_ARB_multitexture
   GL_ARB_occlusion_query
   GL_ARB_occlusion_query2
   GL_ARB_pixel_buffer_object
   GL_ARB_point_parameters
   GL_ARB_point_sprite
   GL_ARB_program_interface_query
   GL_ARB_provoking_vertex
   GL_ARB_robustness
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_seamless_cube_map
   GL_ARB_separate_shader_objects
   GL_ARB_shader_atomic_counters
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_objects
   GL_ARB_shader_precision
   GL_ARB_shader_subroutine
   GL_ARB_shading_language_100
   GL_ARB_shading_language_420pack
   GL_ARB_shading_language_packing
   GL_ARB_shadow
   GL_ARB_stencil_texturing
   GL_ARB_sync
   GL_ARB_tessellation_shader
   GL_ARB_texture_border_clamp
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_buffer_range
   GL_ARB_texture_compression
   GL_ARB_texture_compression_bptc
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_env_add
   GL_ARB_texture_env_combine
   GL_ARB_texture_env_crossbar
   GL_ARB_texture_env_dot3
   GL_ARB_texture_float
   GL_ARB_texture_gather
   GL_ARB_texture_multisample
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_query_lod
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_storage
   GL_ARB_texture_storage_multisample
   GL_ARB_texture_swizzle
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_transform_feedback_instanced
   GL_ARB_transpose_matrix
   GL_ARB_uniform_buffer_object
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_array_object
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_attrib_binding
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_program
   GL_ARB_vertex_shader
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ARB_window_pos
   GL_ATI_separate_stencil
   GL_EXT_abgr
   GL_EXT_bgra
   GL_EXT_blend_color
   GL_EXT_blend_equation_separate
   GL_EXT_blend_func_separate
   GL_EXT_blend_minmax
   GL_EXT_blend_subtract
   GL_EXT_clip_volume_hint
   GL_EXT_compiled_vertex_array
   GL_EXT_draw_buffers2
   GL_EXT_draw_range_elements
   GL_EXT_fog_coord
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_object
   GL_EXT_geometry_shader4
   GL_EXT_gpu_program_parameters
   GL_EXT_gpu_shader4
   GL_EXT_multi_draw_arrays
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_packed_pixels
   GL_EXT_rescale_normal
   GL_EXT_secondary_color
   GL_EXT_separate_specular_color
   GL_EXT_shader_integer_mix
   GL_EXT_shadow_funcs
   GL_EXT_stencil_two_side
   GL_EXT_stencil_wrap
   GL_EXT_texture3D
   GL_EXT_texture_array
   GL_EXT_texture_buffer
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_edge_clamp
   GL_EXT_texture_env_add
   GL_EXT_texture_env_combine
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_lod_bias
   GL_EXT_texture_rectangle
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shared_exponent
   GL_EXT_texture_snorm
   GL_EXT_texture_storage
   GL_EXT_texture_swizzle
   GL_EXT_transform_feedback
   GL_IBM_texture_mirrored_repeat
   GL_INTEL_map_texture
   GL_INTEL_performance_queries
   GL_INTEL_performance_query
   GL_KHR_blend_equation_advanced
   GL_KHR_debug
   GL_NV_blend_square
   GL_NV_conditional_render
   GL_NV_primitive_restart
   GL_NV_texgen_reflection
   GL_SGIS_generate_mipmap
   GL_SGIS_texture_edge_clamp
   GL_SGIS_texture_lod
   GL_SUN_multi_draw_arrays
   GL_WIN_swap_hint
   WGL_ARB_buffer_region
   WGL_ARB_create_context
   WGL_ARB_create_context_profile
   WGL_ARB_create_context_robustness
   WGL_ARB_extensions_string
   WGL_ARB_framebuffer_sRGB
   WGL_ARB_make_current_read
   WGL_ARB_multisample
   WGL_ARB_pbuffer
   WGL_ARB_pixel_format
   WGL_ARB_pixel_format_float
   WGL_EXT_create_context_es2_profile
   WGL_EXT_create_context_es_profile
   WGL_EXT_depth_float
   WGL_EXT_extensions_string
   WGL_EXT_pixel_format_packed_float
   WGL_EXT_swap_control
   WGL_EXT_swap_control_tear
   WGL_NV_DX_interop

pyglet.gl.glx_info
------------------------------------------------------------------------------
GLX not available.

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.directsound.adaptation.DirectSoundDriver object at 0x0000000002B38820>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
OpenAL not available.

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

**How To Reproduce**
`window.width, window.height = 200, 200`

**Comment by einarf** [comment] 2023-03-02 15:38
Do you have the actual code instead of screenshots of the code? The can be pased into the issue with markdown code block and have syntax highlighting even.

**Comment by caffeinepills** [comment] 2023-03-02 15:56
width and height properties should not used to set the size.

If you want to change the size of a window, use `window.set_size(width, height)` to resize.

**Comment by DreamAlone666** [comment] 2023-03-03 04:27
@einarf The actual code is here.

```
import pyglet
from pyglet.shapes import Rectangle

window = pyglet.window.Window(200, 200)
batch = pyglet.graphics.Batch()

rect = Rectangle(100, 100, 100, 100, batch=batch)
label = pyglet.text.Label(batch=batch)
window.width, window.height = 200, 200

@window.event
def on_mouse_motion(x, y, dx, dy):
    label.text = str((x, y))

@window.event
def on_refresh(dt):
    window.clear()
    batch.draw()

pyglet.app.run()
```

**Comment by DreamAlone666** [comment] 2023-03-03 04:38
@caffeinepills
The `width` and `height` property should call `set_size`. I tried agian with `set_size` but in vain.

I then tested it on another Windows 7 device, and got the same result. 
So I guess it may be a Windows7 issue, but I can't work out why.

**Comment by caffeinepills** [comment] 2023-03-03 04:58
I am not 100% sure. Can you try the latest pyglet 1.5 release to see if the issue is still present there? That may atleast tell us if it's related to the migration to 2.0 or if it's some OS issue.

**Comment by DreamAlone666** [comment] 2023-03-03 05:48
I have tried pyglet 1.5.27. It doesn't have this problem.
(Though the size can't be set together using properties like `window.width, window.height = 200, 200`, only the height is changed.)

Is the new OpenGL version can't work well on Windows 7? Or pyglet 2.0 changes something about resizing?

**Comment by caffeinepills** [comment] 2023-03-03 06:48
Pyglet 2.0 uses a newer OpenGL 3.3 while Pyglet 1.5 uses an older OpenGL version for rendering. There may have been changes done that inadvertently affected Windows 7, but nothing comes to mind.

Unfortunately I use Windows 10, so it's hard for me to test. I tried using a Windows 7 VM, and while it creates a window, it doesn't render anything, so my VM isn't much help. I can at least confirm that the position and rectangle report proper sizes. The vertices report properly too: `print(rect.position, rect._vertex_list.vertices[:])`

There is an `on_resize` event. You could try overriding it and playing with the settings to see if it makes any change.
```py
    @window.event
    def on_resize(width, height):
        pyglet.gl.glViewport(0, 0, *window.get_framebuffer_size())
        window.projection = Mat4.orthogonal_projection(0, width, 0, height, -255, 255)
```

**Comment by DreamAlone666** [comment] 2023-03-03 09:50
It should make sense. However, neither the `window.event` decorator nor manually setting it has any effect.
But this surprisely works:

```python
width, height = 250, 200

def on_resize(w, h):
    pyglet.gl.glViewport(0, 0, w, h)
    window.projection = Mat4.orthogonal_projection(0, w, 0, h, -255, 255)
window.on_resize = on_resize

window.set_size(width, height)
```

It can resize the window and render normally now.

**Comment by DreamAlone666** [comment] 2023-03-03 09:51
It should make sense. However, neither the `window.event` decorator nor manually setting it has any effect.
But this surprisely works:

```python
width, height = 250, 200

def on_resize(w, h):
    pyglet.gl.glViewport(0, 0, w, h)
    window.projection = Mat4.orthogonal_projection(0, w, 0, h, -255, 255)
window.on_resize = on_resize

window.set_size(width, height)
```

It can resize the window and render normally now.

**Comment by caffeinepills** [comment] 2023-03-09 16:33
Sorry I didn't reply before. It seems there is a bug in the default `on_resize` event. The one you linked above does work, which is why overriding the original works. We will get this correct. Thank you!

**Comment by caffeinepills** [comment] 2023-03-09 19:39
Should be resolved in https://github.com/pyglet/pyglet/commit/39f69d267548e282fa8d8d27f357f333121c3c8d if you want to confirm with master branch. You should no longer need to overwrite the `on_resize` event.

**Closed** 2023-03-11 17:53 UTC
Labels: bug
