### ISSUE TITLE
Pyglet's Window Display For Apple Silicon (M1, M2) Devices

### ISSUE THREAD

**Issue by abanuelo** [pyglet/pyglet#1100] opened 2024-05-02 20:24 UTC
## Background
I had a question regarding a strange Apple Silicon specific behavior I am facing when working with `pyglet`. I have noticed that if we use `pyglet < 1.5.28` as a dependency for `trimesh` on Apple Silicon devices, after it runs a `show()` from trimesh which uses [a class named SceneViewer](https://github.com/mikedh/trimesh/blob/e7568c6e51c9e74a0f3b0ca278ec53fb4a689021/trimesh/viewer/windowed.py#L36) that has `pyglet <2.0` dependencies to show the screen, when you close out the popped up display window, it completely terminates the program. You can see it best represented in this video in our issues: https://github.com/BerkeleyLearnVerify/Scenic/issues/230

Some more information describing the behavior can be found on this issue from the trimesh side: https://github.com/mikedh/trimesh/issues/2131

However when I downgrade the `pyglet` dependency to say 1.5.26 for trimesh, I am able to close out the opened display window and still have the program continue without crashing. This can be best illustrated by this video here: https://github.com/BerkeleyLearnVerify/Scenic/pull/248

## Question?
Were there any implementation differences between `pyglet` 1.5.26 and 1.5.28 that aren't reflected in the changelog regarding how to handle terminating a opened display window?

**Comment by benmoran56** [comment] 2024-05-06 04:31
The were quite a few bugfixes that were backported, and I believe some changes to the text and font modules. There were also some fixes related to memory leaks and references. 

It might be necessary to do a git bisect to trace down the exact changes. 

The default behavior of the pyglet event loop _is_ to exit when all Windows are closes. The can be overridden of course: https://github.com/pyglet/pyglet/blob/master/pyglet/app/base.py#L277

**Comment by abanuelo** [comment] 2024-05-06 23:38
As a follow up just so we can get some alignment @benmoran56 , what I mean by saying "my program terminates", is that it completely shuts down. To make a more reproducible example for you to replicate try: running this snippet of code with pyglet version `1.5.28`. Once you close out the window, the `print("Will never reach this!!!!!")` never shows and the `while True:` is never re-executed.

```
import pyglet

window = pyglet.window.Window(width=800, height=600)

label = pyglet.text.Label('Hello, Pyglet!',
                          font_name='Arial',
                          font_size=36,
                          x=window.width // 2, y=window.height // 2,
                          anchor_x='center', anchor_y='center')

@window.event
def on_draw():
    window.clear()
    label.draw()

while True:
    pyglet.app.run()
    print("Will never reach this!!!!!")
```

Video:

https://github.com/pyglet/pyglet/assets/32311654/4aac0896-7486-43c5-9fe8-a76dcb859c8a

**Comment by caffeinepills** [comment] 2024-05-07 01:24
I'm not sure we really support looping a `pyglet.app.run()` call, but I think I understand your issue.

I think when the loop terminates it will terminate the whole program for the alternate loop. 
https://github.com/pyglet/pyglet/blob/a728a77cfa94c917c0a375e73e576eac57ffffbf/pyglet/app/cocoa.py#L184-L186

You could try replacing it with this code instead:
```py
    def nsapp_stop(self):
        """Used only for CocoaAlternateEventLoop"""
        self.NSApp.stop_(None)

        if self.timer:
            self.timer.invalidate()
            self.timer = None

        if self.appdelegate:
            self.appdelegate.dealloc()
            self.appdelegate = None
```

**Comment by abanuelo** [comment] 2024-05-07 15:44
That's correct @caffeinepills the alternate loop never gets executed following a closure of the pyglet window after a `pyglet.app.run()`. If we wanted to add that functionality to be able to loop a `pyglet.run.app()`, would it suffice to override the [default behavior](https://github.com/pyglet/pyglet/blob/6e2bf5593272879c03e2610b4cc9735d34c1bdba/pyglet/app/base.py#L279-L280) to run `pass` instead of triggering a `self.exit()` call? Something like this a suppose:

```
def on_window_close(self, window: BaseWindow):
        """Default window close handler."""
        pass
```

**Comment by P-Kaempf** [comment] 2024-05-23 06:40
I have experienced the same. In my case, the error message tells me that all Python threads are terminated. Here is the error message:
Fatal Python error: PyEval_RestoreThread: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

**Comment by caffeinepills** [comment] 2024-06-28 11:16
> That's correct @caffeinepills the alternate loop never gets executed following a closure of the pyglet window after a `pyglet.app.run()`. If we wanted to add that functionality to be able to loop a `pyglet.run.app()`, would it suffice to override the [default behavior](https://github.com/pyglet/pyglet/blob/6e2bf5593272879c03e2610b4cc9735d34c1bdba/pyglet/app/base.py#L279-L280) to run `pass` instead of triggering a `self.exit()` call? Something like this a suppose:
> 
> ```
> def on_window_close(self, window: BaseWindow):
>         """Default window close handler."""
>         pass
> ```

Did my suggested code address your issue with the termination or did you need a more indepth fix?

**Comment by caffeinepills** [comment] 2024-07-13 23:26
@abanuelo Any update on this, or is this ok to close?

**Comment by abanuelo** [comment] 2024-07-13 23:43
@caffeinepills will test this out soon will keep you posted!

**Comment by caffeinepills** [comment] 2024-07-14 00:05
Sounds good, if that still doesn't work, let me know. I am not familiar with trimesh, but if possible, if you can give an example of a basic trimesh script that should work?

Also

1) Does it require the pyglet app to be restarted? If so, why is that?

2) If it's because of the Window, will re-using the same Window be good enough or does it need to be unique each time?

**Comment by caffeinepills** [comment] 2024-09-30 17:51
@abanuelo This should be resolved in #1208 (master branch currently, or next pyglet release)

Let us know if this resolve things on your end.

**Comment by matanox** [comment] 2024-12-25 18:45
@abanuelo just humbly wondering what's the objective of looping the `pyglet.app.run()` and whether it's been confirmed to work now after the above mentioned commits in case it eases my future refactorings of my own application.

**Comment by caffeinepills** [comment] 2024-12-31 18:44
Closing as the original requester has no further issues specified. If you have an issue, create a new request, thanks.

**Closed by caffeinepills** 2024-12-31 18:44 UTC

**Comment by abanuelo** [comment] 2025-01-07 21:45
Following up here @matanox works as required! Just wanted to let you know!

**Comment by matanox** [comment] 2025-01-08 09:02
@abanuelo Thank you, much appreciated, that was important to know!
