### ISSUE TITLE
Randomly getting the following exception

### ISSUE THREAD

**Issue by vibrant** [pyglet/pyglet#160] opened 2020-03-08 22:20 UTC
I'm spawning a bunch of sprites, scaling their images this way after I load them:

`
def scale_image(image, scale=1):
    if scale == 1:
        return image

    image = image.get_image_data()
    texture_width = int(image.width * scale)
    texture_height = int(image.height * scale)
    newdata = c_buffer(texture_width * texture_height * 4)
    gluScaleImage(GL_RGBA,
                  image.width, image.height,
                  GL_UNSIGNED_BYTE,
                  image.get_data('RGBA', image.width * 4),
                  texture_width,
                  texture_height,
                  GL_UNSIGNED_BYTE,
                  newdata)
    return ImageData(texture_width, texture_height, 'RGBA', newdata)
`

and I'm randomly getting the below exception from time to time (1 out of 20-30 times I run the game):

  File "/Users/wojtek/PycharmProjects/lands/client/units.py", line 142, in __init__
    super(Zombie, self).__init__(img=self.anim_spec.idle_animation(self), world_x=x, world_y=y, max_hp=20)
  File "/Users/wojtek/PycharmProjects/lands/client/units.py", line 15, in __init__
    super(Unit, self).__init__(*args, **kwargs)
  File "/Users/wojtek/PycharmProjects/lands/client/base.py", line 43, in __init__
    super(DestructibleSprite, self).__init__(*args, **kwargs)
  File "/Users/wojtek/PycharmProjects/lands/client/base.py", line 11, in __init__
    super().__init__(img, *args, **kwargs)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/sprite.py", line 248, in __init__
    self._create_vertex_list()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/sprite.py", line 394, in _create_vertex_list
    4, vertex_format, 'c4B', ('t3f', self._texture.tex_coords))
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/__init__.py", line 293, in vertex_list
    return _get_default_batch().add(count, 0, None, *data)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/__init__.py", line 371, in add
    vlist = domain.create(count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/vertexdomain.py", line 277, in create
    start = self._safe_alloc(count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/vertexdomain.py", line 247, in _safe_alloc
    return self.allocator.alloc(count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/allocation.py", line 196, in alloc
    self.sizes[-1] += size
IndexError: list index out of range

**Comment by caffeinepills** [comment] 2020-03-08 22:31
If you are using sprites, why not just use `sprite.scale = scale_val` instead of trying to manipulate the image data directly?

**Comment by vibrant** [comment] 2020-03-08 22:35
I had issues with the bounding box for sprite collisions being wrongly calculated when I used sprite scaling.  So I just moved scaling to when loading images in order to avoid that.

**Comment by benmoran56** [comment] 2020-03-11 05:20
@vibrant  If possible could you repost your code with proper formatting? You can put three **\`** marks before and after each code block, on their own line. Such as: 

\`\`\`
code_here()
\`\`\`

Also, are you using threading at all? It sort of smells like a race condition.

**Comment by vibrant** [comment] 2020-03-11 08:15
@benmoran56 Nope, not using threading at all.  I just spawn 100 'enemy' sprites whose images/animations I first scale down using this code:

```
def scale_image(image, scale=1):
    if scale == 1:
        return image

    image = image.get_image_data()
    texture_width = int(image.width * scale)
    texture_height = int(image.height * scale)
    newdata = c_buffer(texture_width * texture_height * 4)
    gluScaleImage(GL_RGBA,
                  image.width, image.height,
                  GL_UNSIGNED_BYTE,
                  image.get_data('RGBA', image.width * 4),
                  texture_width,
                  texture_height,
                  GL_UNSIGNED_BYTE,
                  newdata)
    return ImageData(texture_width, texture_height, 'RGBA', newdata)
```

If I remove the scaling then the app starts up for 30 seconds or more, don't have the patience to check if that eliminates the bug, but just ran it 5 times and it didn't bug out.  I don't scale to a multiple of 2 though so maybe that's the issue?

Pasing the exception that I just reproduced again:
```
Traceback (most recent call last):
  File "/Users/wojtek/PycharmProjects/lands/client/main.py", line 23, in <module>
    from client.game import game
  File "/Users/wojtek/PycharmProjects/lands/client/game.py", line 139, in <module>
    game = Game(width=WIN_WIDTH, height=WIN_HEIGHT)
  File "/Users/wojtek/PycharmProjects/lands/client/game.py", line 50, in __init__
    spawn_initial_enemies(self)
  File "/Users/wojtek/PycharmProjects/lands/client/spawner.py", line 20, in spawn_initial_enemies
    random_spawn(game, Soldier)
  File "/Users/wojtek/PycharmProjects/lands/client/spawner.py", line 11, in random_spawn
    enemy = enemy_class(400 + random.randint(0, 1500), 400 + random.randint(0, 1500)).randrot()
  File "/Users/wojtek/PycharmProjects/lands/client/units.py", line 158, in __init__
    super(Soldier, self).__init__(img=self.anim_spec.idle_animation(self), world_x=x, world_y=y, max_hp=20)
  File "/Users/wojtek/PycharmProjects/lands/client/units.py", line 15, in __init__
    super(Unit, self).__init__(*args, **kwargs)
  File "/Users/wojtek/PycharmProjects/lands/client/base.py", line 43, in __init__
    super(DestructibleSprite, self).__init__(*args, **kwargs)
  File "/Users/wojtek/PycharmProjects/lands/client/base.py", line 11, in __init__
    super().__init__(img, *args, **kwargs)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/sprite.py", line 248, in __init__
    self._create_vertex_list()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/sprite.py", line 394, in _create_vertex_list
    4, vertex_format, 'c4B', ('t3f', self._texture.tex_coords))
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/__init__.py", line 293, in vertex_list
    return _get_default_batch().add(count, 0, None, *data)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/__init__.py", line 371, in add
    vlist = domain.create(count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/vertexdomain.py", line 277, in create
    start = self._safe_alloc(count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/vertexdomain.py", line 247, in _safe_alloc
    return self.allocator.alloc(count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/allocation.py", line 196, in alloc
    self.sizes[-1] += size
IndexError: list index out of range
```

**Comment by benmoran56** [comment] 2020-03-11 08:54
Hmm, the error you're seeing is really strange. I can't see how gluScale would have any effect on the allocator code. 
For good measure, could you throw a call to `glFlush()` at the end of your scale method?

Going back to your original issue, what problem were you running into with the bounding box calculations? Fixing that might be the simplest way to go, and would be more performant.

**Comment by vibrant** [comment] 2020-03-12 11:18
@benmoran56 another one I just got :)

```
Traceback (most recent call last):
  File "/Users/wojtek/PycharmProjects/lands/client/main.py", line 24, in <module>
    from client.game import game
  File "/Users/wojtek/PycharmProjects/lands/client/game.py", line 137, in <module>
    game = Game(width=WIN_WIDTH, height=WIN_HEIGHT)
  File "/Users/wojtek/PycharmProjects/lands/client/game.py", line 52, in __init__
    spawn_initial_enemies(self)
  File "/Users/wojtek/PycharmProjects/lands/client/spawner.py", line 25, in spawn_initial_enemies
    random_spawn(game, Zombie)
  File "/Users/wojtek/PycharmProjects/lands/client/spawner.py", line 19, in random_spawn
    game.add_collidable_sprite(enemy)
  File "/Users/wojtek/PycharmProjects/lands/client/game.py", line 64, in add_collidable_sprite
    sprite.batch = self.sprites_batch
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/sprite.py", line 316, in batch
    self._vertex_list.delete()
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/vertexdomain.py", line 414, in delete
    self.domain.allocator.dealloc(self.start, self.count)
  File "/Users/wojtek/PycharmProjects/lands/venv/lib/python3.7/site-packages/pyglet/graphics/allocation.py", line 308, in dealloc
    assert p >= 0 and size <= alloc_size - p, 'Region not allocated'
AssertionError: Region not allocated
```

**Comment by benmoran56** [comment] 2020-05-18 07:48
@vibrant The `AssertionError: Region not allocated` is caused by attempting to delete a vertex list (or sprite) that has already been deleted.

**Comment by benmoran56** [comment] 2021-04-19 08:12
Closing due to lack of reply, but please follow up if you're still seeing issues.

**Closed by benmoran56** 2021-04-19 08:12 UTC

**Comment by Whiax** [comment] 2024-07-16 01:55
Hi! I'm having the same issue with pyglet 2.0.16.

The error also happens randomly, it's quite hard to reproduce consistently but it happens after I attribute a sprite to a batch. 
I'm doing something a bit like.

```
Loop:
  my_img = ...
  spr1 = Sprite(img=my_img)
  ...
  spr2 = Sprite(img=my_img)
  spr2.batch = my_batch
```


traceback:
```
  File ((mycode.py))
    "spr2.batch = my_batch"

  File pyglet\sprite.py:435 in batch
    self._vertex_list.delete()

  File pyglet\graphics\vertexdomain.py:267 in delete
    super().delete()

  File pyglet\graphics\vertexdomain.py:157 in delete
    self.domain.allocator.dealloc(self.start, self.count)

  File pyglet\graphics\allocation.py:264 in dealloc
    assert p >= 0 and size <= alloc_size - p, 'Region not allocated'  # noqa: PT018

AssertionError: Region not allocated
```

Values for p, size and alloc_size are: -48, 4, 4

It seems that I also have the following issue which looks like it's related (same inconsistency / difficulty to reproduce / around the same code). This one is when I create the sprite.

traceback:
```
  File ((mycode.py))
    "spr1 = Sprite(img=my_img)"

  File pyglet\sprite.py:334 in __init__
    self._create_vertex_list()

  File pyglet\sprite.py:496 in _create_vertex_list
    self._vertex_list = self.program.vertex_list_indexed(

  File pyglet\graphics\shader.py:1346 in vertex_list_indexed
    return self._vertex_list_create(count, mode, indices, None, batch=batch, group=group, **data)

  File pyglet\graphics\shader.py:1284 in _vertex_list_create
    vlist = domain.create(count, len(indices))

  File pyglet\graphics\vertexdomain.py:694 in create
    start = self.safe_alloc(count)

  File pyglet\graphics\vertexdomain.py:425 in safe_alloc
    return self.allocator.alloc(count)

  File pyglet\graphics\allocation.py:136 in alloc
    del self.starts[i + 1]

IndexError: list assignment index out of range

```
I'm not sure on how to debug this issue. I'm probably doing something wrong but I don't know where the issue is or how to solve it.

**Comment by Whiax** [comment] 2024-07-16 19:02
Minimal code to reproduce:

1) put a debug.png near the script
2) run the code for a bit of time (<5minutes, 2000~10000 iterations, very inconsistent)
3) **AssertionError: Region not allocated** will happen randomly after some time

```
from pyglet.gl import *
import pyglet

#init
window = pyglet.window.Window(800, 600, resizable=True)
batch = pyglet.graphics.Batch()

#MySprite
class MySprite:
    cache_e_to_imgs = {}
    def __init__(self, e):
        
        if not e in MySprite.cache_e_to_imgs:
            MySprite.cache_e_to_imgs[e] = [pyglet.resource.texture(f'{e}.png')]
        
        imgs = MySprite.cache_e_to_imgs[e]
        anim = [pyglet.sprite.Sprite(img=img) for img in imgs]
        self.anim, self.frames = anim, imgs

#Visual component of an object
class MyVisualObject:
    def __init__(self, obj):
        self.object = obj
        
    #init sprite or skeleon
    def init(self, e=None):
        self.v = MySprite(self.object.name)

#An object
class MyObject:
    def __init__(self,name):
        self.name = name
        self.v = MyVisualObject(self)
        self.v.init()


data = {'i':0}
@window.event
def on_draw():
    glClearColor(.7,.7,.7,1)
    window.clear()
    
    #new_obj
    new_obj = MyObject('debug')
    img = new_obj.v.v.frames[0]
    
    print(data['i'], 'id(texture):', id(img))
    spr = pyglet.sprite.Sprite(img=img)
    spr.batch = batch
    
    data['i'] += 1
    batch.draw()

pyglet.app.run()
```
