### ISSUE TITLE
Left shift key and right shift key emit the same key code: 65505 (0xffe1)

### ISSUE THREAD

**Issue by nejinx** [pyglet/pyglet#320] opened 2020-11-30 10:00 UTC
Whether you press the left shift or right shift key, the same key code is emitted: **65505 (0xffe1)**.

The right shift key is meant to emit key code: **65506 (0xffe2)**

Example code:
```
import pyglet

class TestShiftKey(pyglet.window.Window):
    def __init__(self):
        super().__init__()

    def on_key_press(self, symbol, modifiers):
        print("Symbol:", symbol, hex(symbol))

if __name__ == '__main__':
    TestShiftKey()
    pyglet.app.run()

```

I suspect this might have something to do with it:

https://github.com/pyglet/pyglet/blob/bc6558a4b4e842f2fe1e7fa82d7d0ca43e92a3dd/pyglet/window/win32/__init__.py#L771-L773

**Comment by nejinx** [comment] 2020-11-30 10:11
Just to clarify I am running it under Windows 10.

**Comment by einarf** [comment] 2020-11-30 11:00
Related issue : https://github.com/pythonarcade/arcade/issues/789

**Comment by caffeinepills** [comment] 2020-12-03 21:32
I looked into this, and these seem to be handled differently due to some of the first keyboards not having a right shift. While I can fix this for left and right shift keys. There are some issues that will break consistency with all the other keys. 

The problem comes in when both keys are pressed at the same time.

1) Holding down one shift, and pressing another will not fire a key down event for the new shift. 

2) Holding down both shifts and releasing one shift will not trigger a shift event.

Therefore: Holding left shift down, then right shift, then releasing left shift then right shift. You will NOT get a left shift up, nor a right shift down, only right shift up. This will break the key state handler as you will have left shift still showing as down and the right shift up will not have been shown as being down at any time.

Windows doesn't seem to recognize this case scenario. The problem is, every other key does not behave like this. Every other key will register both downs and ups regardless of what else is being held down at the time.

Any suggestions on a way to resolve this would be appreciated.

**Comment by benmoran56** [comment] 2020-12-05 14:05
Now the code comment starts making sense :smile: 
```# TODO: some magic with getstate to find out if it's the right or left shift key. ```

From your testing though, it doesn't sound like this would be possible to make work. We could internally log the DOWN events, and then guess about trying to send duplicate UP events to make up for "missing" events, but they would be delayed. We would still be missing the extra DOWN events, so it's not really a solution. 

I guess the question to clarify is whether or not this is just the way it's implemented on Windows. In that case, in my opinion it would be better to keep the current behavior in pyglet, rather than potentially breaking key handlers and such.

**Comment by caffeinepills** [comment] 2020-12-08 16:48
While we do technically get a new `WM_KEYDOWN` for the second shift, the problem is due to the fact we use the previous key state to determine if the key is a repeat key so we only dispatch one `on_key_press` or `on_key_down` event. This event seems to work as we expect in all other key cases except this scenario with SHIFT. We *may* be able to get this to work with some magic and internal shift key states, but that's providing the other points are resolved.

From what I have investigated with other libraries, they have a lot of hacks to make this work.

First, is that the event loop checks shift key states every loop to determine if it was released. This differs from pyglet, as key events come from the Window, not the event loop. We would have to add a way to add specific custom functions to be called from the event loop **after** all Window events have been processed. Cannot use scheduling as this would make the Window reliant on the clock for proper key states, and might not guarantee it was called after the windows key state was set. Is it worth the performance penalty (no matter how miniscule) to check key states every frame to hack fix one key? 

Secondly they have an internal key state they modify, which we do not have as here it's an optional handler. GLFW also seems to release both shift states automatically when one shift is released. So if you had two shifts held down, released one, it would call shift release on both. Not sure that would work.

I guess it depends on how many work arounds pyglet will tolerate for a fix.

The only other thing I saw that _may_ work from initial testing and digging, was using raw input devices with `WM_INPUT`. This seems to be the 'newest' method to do key states. From what I read in the docs in raw inputs they refer to `WM_KEYDOWN`, `WM_KEYUP`, etc as 'legacy'. However, I have no idea or experience in how this may affect keyboard devices. Would we lose functionality in some cases? Are there cases someone wouldn't get input with some keyboards? Is it faster, slower? I have no idea.

**Comment by benmoran56** [comment] 2020-12-09 09:48
Thanks for taking a deep dive into that. I've been doing a bit of reading about this also, and I agree that WM_INPUT seems like the way to go.  I only did a small bit of poking around in my VM, but we're already getting raw input for the mouse - in exclusive mode. I suppose it's limited to exclusive mode, since they you don't have to worry about the various mouse_in/out events and stuff like that.  Anyways, it doesn't seem too difficult to grab this data for Keyboards as well. The first step should be to register the raw input devices. The mouse-only is registered like this: 
```py
raw_mouse = RAWINPUTDEVICE(0x01, 0x02, 0, None)
...
_user32.RegisterRawInputDevices(byref(raw_mouse), 1, sizeof(RAWINPUTDEVICE))
```

Then there is a handler defined for it: 
```py
    @ViewEventHandler
    @Win32EventHandler(WM_INPUT)
    def _event_raw_input(self, msg, wParam, lParam):
            ...
            if rmouse.usButtonFlags & RI_MOUSE_LEFT_BUTTON_DOWN:
                self.dispatch_event('on_mouse_press', 0, 0, mouse.LEFT,
                                    self._get_modifiers())
            ...
```

I think a good test plan would be to rename the existing one to (`_event_raw_mouse_input`), and then make a new keyboard raw input handler such as (`_event_raw_keyboard_input`). We _should_ then be able to peek at the raw input values from the keyboard, as long as `_user32.RegisterRawInputDevices(....)` is called in `__init__`. I'm not sure if you can call this function twice, or you need to register all devices at once, but the mouse registration can be commented out for a quick test. 

If all that works, then the easiest solution might be to: 
1. skip over any SHIFT events from the KEY_UP/DOWN handlers
2. look for the SHIFT events *only* in the new raw handler, and then dispatch from there. 

I'm not yet sure if it makes sense to switch all of the input over to raw yet. I think there might be some extra work involved with regards to keyboard layouts, and other things like WM_CHAR needing to be emulated. (We're using WM_CHAR for the `self.dispatch_event('on_text', text)` events).

**Comment by caffeinepills** [comment] 2020-12-10 15:47
I have messed with raw input to get a work around so that this works and setup a PR.

#326 

I have tested this on Windows 10 without any issues, but if any of you want to test before this gets merged in, I'd appreciate it. @einarf @nejinx

**Comment by nejinx** [comment] 2020-12-11 01:33
Shift keys are now working correctly when testing this change. Awesome job! 👍  @caffeinepills

**Comment by benmoran56** [comment] 2020-12-22 12:40
This has been included with the latest pyglet release, so I'll close this. 
Thanks everyone!

**Closed by benmoran56** 2020-12-22 12:40 UTC
