### ISSUE TITLE
OSError because of Python Garbage Collector when using pyglet.media.Player

### ISSUE THREAD

**Issue by chcarmen** [pyglet/pyglet#113] opened 2019-12-26 13:46 UTC
Hi, everyone, I encountered a issue recently.
When I run the following code:
```
music_player = pyglet.media.Player()
music_player.queue(pyglet.resource.media("win.mp3", streaming=True))
music_player.play()
```
It causes an exception:
```
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x038B6070>
Traceback (most recent call last):
  File "xxx\pyglet\media\drivers\directsound\interface.py", line 174, in __del__
    self.delete()
  File "xxx\pyglet\media\drivers\directsound\interface.py", line 180, in delete
    self._native_buffer.Stop()
  File "xxx\pyglet\com.py", line 131, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
OSError: exception: access violation writing 0x00000000
```
while the following code works well:
```
def play_music():
    music_player = pyglet.media.Player()
    music_player.queue(pyglet.resource.media("win.mp3", streaming=True))
    music_player.play()

play_music()
```
I guess this is related to python garbage collgector mechanism and pyglet.media.Player()'s  __del__ function, but I am really not sure about how to fix this issue. So any ideas from you guys?

**Comment by caffeinepills** [comment] 2019-12-26 17:29
I have noticed this as well, and it's quite an annoying issue. IIRC it used to not do this and it caused memory leaks, so that's why it was changed. I think it needs a more graceful solution because it's not intuitive at all for people.

The only work around I've found is to store the players so they don't get GC'd. 
```
players = []

player = Player()
player.queue(media)
player.play()
players.append(player)

def _on_player_eos():
    players.remove(player)
    player.on_player_eos = None

player.on_player_eos = _on_player_eos
```

**Comment by chcarmen** [comment] 2019-12-27 01:23
Thanks caffeinepills  for your reply, but unfortunatly the workaround you provided still doesn't work for me.
the complete code i run is below:
```
import pyglet
import pyglet_ffmpeg2

music_player = pyglet.media.Player()
music_player.queue(pyglet.resource.media("win.mp3", streaming=True))
music_player.play()
```
if convenient, you can also give it a try. Actually, I found this issue in my project which has quite more code than above, every time i close the program window, it shows exception like I mentioned previously, so I just simplified my code to above to make things specific. And also, yes, I need to get a   `pyglet.media.Player()` object to control the music. 
I just want to know what does the following code do when exception happens? and are there any finnal solutions about this issue?
`ret = self.method.get_field()(self.i, self.name)(obj, *args)`

**Comment by chcarmen** [comment] 2020-01-03 13:40
Here are just some updates.
Radomly, the following code appears exception when program exits:
1. `assert _debug() ` in functions `DirectSoundListener.\_\_del\_\_` `DirectSoundDriver.__del__` `DirectSoundBufferFactory.__del__` `DirectSoundBuffer.__del__`
2. `self._native_buffer.Stop()` in function `DirectSoundBuffer.__del__` (`delete()`)
Both of them have the same reason, by the time when garbage collected, `_debug` is None or the C function `self._native_buffer.Stop()` calls to is unaccessible (ctypes module already gets destroied )

**Comment by benmoran56** [comment] 2020-01-21 09:40
Thanks for the additional information @chcarmen about the `_debug` global.
On one hand, the debug is useful for visual debugging, but it does sound like it's not the right place for it.

**Comment by benmoran56** [comment] 2020-01-23 09:17
Could you give it a try with the latest 1.5-maintenance branch? The global debug method is no longer used in the `__del__` methods.

**Comment by t-o-n-y-p** [comment] 2020-02-01 14:01
Reproducibe with the latest 1.5-maintenance branch.
#141

**Comment by chcarmen** [comment] 2020-02-06 12:16
Hello Benjamin,
sorry for late response, because of the holiday here.
first, using the latest 1.5-maintenance branch, the exception raised from ` _debug()` does disappear.
but, seems it brings a new random exception when playing music:
```
Traceback (most recent call last):
  File "xxx\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "xxx\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "xxx\lib\site-packages\pyglet\media\player.py", line 59, in _tick_clock
    self.tick()
  File "xxx\lib\site-packages\pyglet\clock.py", line 348, in tick
    self.call_scheduled_functions(delta_t)
  File "xxx\lib\site-packages\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "xxx\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 173, in _check_refill
    self.refill(write_size)
  File "xxx\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 178, in refill
    audio_data = self._get_audiodata()
  File "xxx\venv3.8\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 199, in _get_audiodata
    self._get_new_audiodata()
  File "xxx\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 207, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "xxx\lib\site-packages\pyglet\media\drivers\base.py", line 144, in get_audio_time_diff
    p_time = self.player.time
ReferenceError: weakly-referenced object no longer exists
```

and also, this exception still exsits:
```
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x038B6070>
Traceback (most recent call last):
  File "xxx\pyglet\media\drivers\directsound\interface.py", line 174, in __del__
    self.delete()
  File "xxx\pyglet\media\drivers\directsound\interface.py", line 180, in delete
    self._native_buffer.Stop()
  File "xxx\pyglet\com.py", line 131, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
OSError: exception: access violation writing 0x00000000
```

**Comment by benmoran56** [comment] 2020-02-17 07:45
Hi everyone, sorry for the long delay with this! 

I think it should be OK now with the latest 1.5 release, so if someone else could confirm that would be great!

**Comment by chcarmen** [comment] 2020-02-19 03:02
Thanks Benjamin for your work!
All exceptions disapper with the version 1.5 release , except for this one:
```
Exception ignored in: <function DirectSoundBuffer.__del__ at 0x038B6070>
Traceback (most recent call last):
  File "xxx\pyglet\media\drivers\directsound\interface.py", line 169, in __del__
    self.delete()
  File "xxx\pyglet\media\drivers\directsound\interface.py", line 173, in delete
    self._native_buffer.Stop()
  File "xxx\pyglet\com.py", line 138, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
OSError: exception: access violation writing 0x00000000
```
I think it may be releated to pyglet overall resource clearing mechanism.

**Comment by benmoran56** [comment] 2020-05-06 04:28
Sorry for the long delay on this. I pushed a workaround to the pyglet-1.5-maintenance branch. It should prevent the error caused by `__del__` attempting to delete an already deleted buffer when garbage collected.

**Comment by benmoran56** [comment] 2021-02-02 03:12
Closing, as this is fixed in the latest releases.

**Closed by benmoran56** 2021-02-02 03:12 UTC
Labels: bug
