### ISSUE TITLE
Window on_press events don't work on MacOS 

### ISSUE THREAD

**Issue by Artur-Galstyan** [pyglet/pyglet#895] opened 2023-07-15 21:00 UTC
Steps to reproduce:

0. Buy a Macbook
1. Take the code from the docs:

```python
import pyglet

window = pyglet.window.Window()

@window.event
def on_key_press(symbol, modifiers):
    print('A key was pressed')

@window.event
def on_draw():
    window.clear()

pyglet.app.run()
```

2. Press a key
3. Nothing happens in the console :( 

It seems that event is not being fired as nothing is printed in the console.

**Comment by HauseMasterZ** [comment] 2023-07-16 10:31
If you just need to register text then try using on_text(text). I think this is a known issue in macOS.

**Comment by benmoran56** [comment] 2023-07-18 03:19
I can't reproduce this with. 
Which version of pyglet are you using? (`pyglet.version`)

**Comment by caffeinepills** [comment] 2023-07-20 00:46
Any followup on what version of pyglet or Mac OS?

**Comment by Artur-Galstyan** [comment] 2023-07-20 13:08
Hi, sorry for the late response.

The version is:
pyglet = "^2.0.8"

But it turns out, that `on_text(text)` works! So, I'm now using that to check for key presses. If it's a known issue, I guess we can close this issue. Perhaps it would be nice to add that to the docs.

**Comment by lyonserdar** [comment] 2023-07-20 21:05
I had the same issue on mac. Just tested it in master and it is working.

**Comment by caffeinepills** [comment] 2023-07-21 15:43
> I had the same issue on mac. Just tested it in master and it is working for `on_key_press`. However, i didn't register any input from `key.KeyStateHandler`.

I tested the `KeyStateHandler` and can confirm it's working. Can you give your code example to where this isn't working?

**Comment by lyonserdar** [comment] 2023-07-21 16:19
My bad! I tested it again and it is working. When it wasn't working I added some code to get it working and forgot to remove it.

**Comment by caffeinepills** [comment] 2023-07-21 16:46
No worries, just wanted to confirm! Thanks for your help! We will close this since it is fixed in master currently.

**Closed by caffeinepills** 2023-07-21 16:46 UTC
Labels: bug
