### ISSUE TITLE
Attempting to create a windows in Python 3.13 crashes immediately

### ISSUE THREAD

**Issue by syegulalp** [pyglet/pyglet#1196] opened 2024-08-29 16:53 UTC
**Describe the bug**
Pyglet crashes when creating a window in Python 3.13rc1.
Traceback:

```
Traceback (most recent call last):
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\__init__.py", line 407, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Work projects\ast-demo\pg.py", line 7, in <module>
    window = pyglet.window.Window(width=1080, height=720)
             ^^^^^^^^^^^^^^^^^^^^
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\__init__.py", line 413, in __getattr__
    __import__(import_name)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\window\__init__.py", line 101, in <module>
    from pyglet.graphics import shader
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\graphics\__init__.py", line 16, in <module>
    from pyglet.gl.gl import (
    ...<13 lines>...
    )
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\gl\__init__.py", line 184, in <module>
    from .win32 import Win32Config as Config
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\gl\win32.py", line 6, in <module>
    from pyglet.canvas.win32 import Win32Canvas
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\canvas\__init__.py", line 46, in <module>
    from pyglet.canvas.win32 import Win32Display as Display
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\canvas\win32.py", line 3, in <module>
    from pyglet.libs.win32 import _user32
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\libs\win32\__init__.py", line 6, in <module>
    from . import com
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\libs\win32\com.py", line 226, in <module>
    class IUnknown(Interface):
    ...<4 lines>...
        ]
  File "F:\Work projects\ast-demo\.venv313\Lib\site-packages\pyglet\libs\win32\com.py", line 154, in __new__
    _pInterfaceMeta(f"p{name}", (ctypes.POINTER(bases[0]),), {'_type_': res_type})  
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
TypeError: _type_ must have storage info
```

**How To Reproduce**
This snippet alone produces the problem.
```py
import pyglet
window = pyglet.window.Window(width=1080, height=720)
```

**Comment by benmoran56** [comment] 2024-08-30 00:24
Thanks for the report. I recently tested the 3.13 free-threaded build with success, so maybe a bug or some last minute Python changes. I'll give it a try on my end.

**Comment by benmoran56** [comment] 2024-08-31 07:48
Confirmed in my Windows VM.

**Comment by benmoran56** [comment] 2024-09-01 00:14
The error is being triggered from here, related to some PRs that went into CPython about 6 months ago:
https://github.com/python/cpython/blame/5332d989af45378e6ae99aeda72bfa82042b8659/Modules/_ctypes/_ctypes.c#L1160
This PR: https://github.com/python/cpython/issues/114314

We need to figure out what we're doing that causes the issue, and then see if it's something we're doing wrong, or a new edge-case bug.

**Comment by Square789** [comment] 2024-09-01 01:38
Probably my fault since i made pretty massive changes in that module a few months back.
I think the current implementation uses non-public metaclasses in like two instances, which definitely ties into the error somehow. Release of 3.13 isn't too far away anymore now, i'll take a look

**Comment by Square789** [comment] 2024-09-01 06:38
The [code before my rewrite](https://github.com/pyglet/pyglet/blob/20a26ab410af91611f83a7accb84c3a772b7be44/pyglet/libs/win32/com.py#L198) breaks in 3.13 too, although in a stranger way where a multiple-inheritance metaclass (`COMPointerMeta`) that - if you look at it now never should've worked to begin with - started following its MI rules in 3.13 and routed `super().__new__` into `COMInterfaceMeta.__new__` (instead of `type.__new__`), which required `COMInterface` to exist, which doesn't work out. Well, it's overwritten code, i'm just not going to question any of that.

The good news is that the fix for the cpython change is relatively simple. The supplied type indeed has no storage info, as the relevant initialization was moved to `PyCStructType_init` instead of `PyCStructType_new`, so we can't expect to create any linked pointer instances in `__new__` anymore.
Simply moving that part to `__init__` seems to do the trick and additionally not cause any problems down to 3.8.

**Comment by benmoran56** [comment] 2024-09-03 04:25
Thank you @Square789!  
Confirmed this is fixed on my side as well. I'll resolve this ticket, and see about getting a point release out soon.

**Closed by benmoran56** 2024-09-03 04:25 UTC
Labels: bug, windows, reproducible
