### ISSUE TITLE
Default shaders do not yet support drawing without first binding a Texture.

### ISSUE THREAD

**Issue by branden-akana** [pyglet/pyglet#117] opened 2020-01-03 14:32 UTC
After updating Pyglet to `2.0.dev0` to experiment with the shaders, it seems that my draw calls now don't do anything. I was able to track the cause down to this statement in [shader.py](https://github.com/pyglet/pyglet/blob/master/pyglet/graphics/shader.py#L3):
```python
from pyglet.graphics.vertexbuffer import create_buffer
```

I wrote a small program demonstrating it. It draws a triangle on the screen:

```python
import pyglet
# import pyglet.graphics.vertexbuffer

window = pyglet.window.Window()

batch = pyglet.graphics.Batch()
batch.add(3, pyglet.gl.GL_TRIANGLES, None,
          ("vertices2f", (0, 0, 100, 100, 100, 0)),
          ("colors3B", (255, 255, 255) * 3))

@window.event
def on_draw():
    window.clear()
    batch.draw()

pyglet.app.run()
```
![image](https://user-images.githubusercontent.com/4042962/71728538-6c888800-2de1-11ea-970d-e4385da0684c.png)
---
Uncommenting `import pyglet.graphics.vertexbuffer` causes it to not display anything. I have no idea why this happens, but maybe someone has an idea.

Tested this using Python 3.7.3 and 3.8.0.

**Comment by einarf** [comment] 2020-01-03 17:01
I can reproduce this issue on OS X as well. Been trying to figure it out.

**Comment by branden-akana** [comment] 2020-01-04 04:23
It seems the cause is the default shaders in [`__init__.py`](https://github.com/pyglet/pyglet/blob/master/pyglet/graphics/__init__.py#L726-L764).

The problem is the default fragment shader:
```python
    void main()
    {
        final_colors = texture(our_texture, texture_coords) + vertex_colors;
    }
```
which uses a sampled texture as a part of the final fragment color. However, since there's no texture bound yet (I'm just drawing a shape), it always samples black.

I was able to get around this by making a shader that's an exact copy of the default one, except the final color in the fragment shader is changed to `final_colors = vertex_colors;`, then using that program in a group when I add vertex lists to the batch. Alternatively, if I load an image and bind it with `glBindTexture(GL_TEXTURE_2D, image.get_texture().id)`, it also works.

Not sure the best way to address this in the repo though since I'm not that experienced with GL.

**Comment by benmoran56** [comment] 2020-01-07 00:52
Thanks for taking the time to dig into this @branden-akana. That definitely makes sense. The goal, if possible, is to support both use cases in the default shaders.  I also don't know if that's possible, but if not, we can just have multiple default shaders (and choose the appropriate one when creating the vertex list). This is related to #115 :)

**Comment by benmoran56** [comment] 2020-04-10 15:00
I was looking into this, and it seems there is more to it than just the shader. Setting the glClearColor in draw illustrates it:
```
@window.event
def on_draw():
    pyglet.gl.glClearColor(0.5, 0.5, 0.5, 1)
    window.clear()
    batch.draw()
```
It seems like the triangle is not just sampling the wrong colors, but is not drawn at all. Or, it's being drawn off-screen due to the projection.  I'll have a look into it further.

**Comment by benmoran56** [comment] 2020-04-11 14:08
This should be one step closer to working now. On my machine (Linux, AMD + MESA), the triangle would not draw at all with the extra import statement. The early import was causing the default Shader Program to be linked on the shadow window/context, rather than the real Window/context. To make it more robust, the default shader now gets linked once per context as required. 

It's actually working OK with the default shader now on my machine, despite having no texture bound. If someone else could give this a try with the latest code from master, that would be great!

**Comment by einarf** [comment] 2020-04-18 14:10
Just tested with latest master. It renders the batch fine with the import 👍 (on OS X)

**Comment by benmoran56** [comment] 2020-04-19 07:12
Thanks! Confirmed on my Linux machines as well. I'll close this for now, but if anyone has anything else to add, please reopen it or comment!

**Closed by benmoran56** 2020-04-19 07:12 UTC
